# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Content

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ChunkRouteSample(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 56

    # ChunkRouteSample
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ChunkRouteSample
    def DistanceMeters(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # ChunkRouteSample
    def LateralMeters(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))
    # ChunkRouteSample
    def ElevationMeters(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(12))
    # ChunkRouteSample
    def Curvature(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(16))
    # ChunkRouteSample
    def Grade(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(20))
    # ChunkRouteSample
    def ProjectedXMeters(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(24))
    # ChunkRouteSample
    def ProjectedYMeters(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(32))
    # ChunkRouteSample
    def ProjectedTangentX(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(40))
    # ChunkRouteSample
    def ProjectedTangentY(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(48))

def CreateChunkRouteSample(builder, distanceMeters, lateralMeters, elevationMeters, curvature, grade, projectedXMeters, projectedYMeters, projectedTangentX, projectedTangentY):
    builder.Prep(8, 56)
    builder.PrependFloat64(projectedTangentY)
    builder.PrependFloat64(projectedTangentX)
    builder.PrependFloat64(projectedYMeters)
    builder.PrependFloat64(projectedXMeters)
    builder.PrependFloat32(grade)
    builder.PrependFloat32(curvature)
    builder.PrependFloat32(elevationMeters)
    builder.PrependFloat32(lateralMeters)
    builder.PrependFloat64(distanceMeters)
    return builder.Offset()


class ChunkRouteSampleT(object):

    # ChunkRouteSampleT
    def __init__(
        self,
        distanceMeters = 0.0,
        lateralMeters = 0.0,
        elevationMeters = 0.0,
        curvature = 0.0,
        grade = 0.0,
        projectedXMeters = 0.0,
        projectedYMeters = 0.0,
        projectedTangentX = 0.0,
        projectedTangentY = 0.0,
    ):
        self.distanceMeters = distanceMeters  # type: float
        self.lateralMeters = lateralMeters  # type: float
        self.elevationMeters = elevationMeters  # type: float
        self.curvature = curvature  # type: float
        self.grade = grade  # type: float
        self.projectedXMeters = projectedXMeters  # type: float
        self.projectedYMeters = projectedYMeters  # type: float
        self.projectedTangentX = projectedTangentX  # type: float
        self.projectedTangentY = projectedTangentY  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        chunkRouteSample = ChunkRouteSample()
        chunkRouteSample.Init(buf, pos)
        return cls.InitFromObj(chunkRouteSample)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, chunkRouteSample):
        x = ChunkRouteSampleT()
        x._UnPack(chunkRouteSample)
        return x

    # ChunkRouteSampleT
    def _UnPack(self, chunkRouteSample):
        if chunkRouteSample is None:
            return
        self.distanceMeters = chunkRouteSample.DistanceMeters()
        self.lateralMeters = chunkRouteSample.LateralMeters()
        self.elevationMeters = chunkRouteSample.ElevationMeters()
        self.curvature = chunkRouteSample.Curvature()
        self.grade = chunkRouteSample.Grade()
        self.projectedXMeters = chunkRouteSample.ProjectedXMeters()
        self.projectedYMeters = chunkRouteSample.ProjectedYMeters()
        self.projectedTangentX = chunkRouteSample.ProjectedTangentX()
        self.projectedTangentY = chunkRouteSample.ProjectedTangentY()

    # ChunkRouteSampleT
    def Pack(self, builder):
        return CreateChunkRouteSample(builder, self.distanceMeters, self.lateralMeters, self.elevationMeters, self.curvature, self.grade, self.projectedXMeters, self.projectedYMeters, self.projectedTangentX, self.projectedTangentY)
