# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Content

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ChunkManifestData(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ChunkManifestData()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsChunkManifestData(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def ChunkManifestDataBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x43\x42\x52\x47", size_prefixed=size_prefixed)

    # ChunkManifestData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ChunkManifestData
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ChunkManifestData
    def EdgeId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ChunkManifestData
    def StartMeters(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # ChunkManifestData
    def EndMeters(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # ChunkManifestData
    def ContentHash(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ChunkManifestData
    def RelativePath(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ChunkManifestData
    def ProbableBranchChunkIds(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # ChunkManifestData
    def ProbableBranchChunkIdsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ChunkManifestData
    def ProbableBranchChunkIdsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

def ChunkManifestDataStart(builder):
    builder.StartObject(7)

def Start(builder):
    ChunkManifestDataStart(builder)

def ChunkManifestDataAddId(builder, id):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)

def AddId(builder, id):
    ChunkManifestDataAddId(builder, id)

def ChunkManifestDataAddEdgeId(builder, edgeId):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(edgeId), 0)

def AddEdgeId(builder, edgeId):
    ChunkManifestDataAddEdgeId(builder, edgeId)

def ChunkManifestDataAddStartMeters(builder, startMeters):
    builder.PrependFloat64Slot(2, startMeters, 0.0)

def AddStartMeters(builder, startMeters):
    ChunkManifestDataAddStartMeters(builder, startMeters)

def ChunkManifestDataAddEndMeters(builder, endMeters):
    builder.PrependFloat64Slot(3, endMeters, 0.0)

def AddEndMeters(builder, endMeters):
    ChunkManifestDataAddEndMeters(builder, endMeters)

def ChunkManifestDataAddContentHash(builder, contentHash):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(contentHash), 0)

def AddContentHash(builder, contentHash):
    ChunkManifestDataAddContentHash(builder, contentHash)

def ChunkManifestDataAddRelativePath(builder, relativePath):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(relativePath), 0)

def AddRelativePath(builder, relativePath):
    ChunkManifestDataAddRelativePath(builder, relativePath)

def ChunkManifestDataAddProbableBranchChunkIds(builder, probableBranchChunkIds):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(probableBranchChunkIds), 0)

def AddProbableBranchChunkIds(builder, probableBranchChunkIds):
    ChunkManifestDataAddProbableBranchChunkIds(builder, probableBranchChunkIds)

def ChunkManifestDataStartProbableBranchChunkIdsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartProbableBranchChunkIdsVector(builder, numElems):
    return ChunkManifestDataStartProbableBranchChunkIdsVector(builder, numElems)

def ChunkManifestDataEnd(builder):
    return builder.EndObject()

def End(builder):
    return ChunkManifestDataEnd(builder)

try:
    from typing import List
except:
    pass

class ChunkManifestDataT(object):

    # ChunkManifestDataT
    def __init__(
        self,
        id = None,
        edgeId = None,
        startMeters = 0.0,
        endMeters = 0.0,
        contentHash = None,
        relativePath = None,
        probableBranchChunkIds = None,
    ):
        self.id = id  # type: Optional[str]
        self.edgeId = edgeId  # type: Optional[str]
        self.startMeters = startMeters  # type: float
        self.endMeters = endMeters  # type: float
        self.contentHash = contentHash  # type: Optional[str]
        self.relativePath = relativePath  # type: Optional[str]
        self.probableBranchChunkIds = probableBranchChunkIds  # type: Optional[List[Optional[str]]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        chunkManifestData = ChunkManifestData()
        chunkManifestData.Init(buf, pos)
        return cls.InitFromObj(chunkManifestData)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, chunkManifestData):
        x = ChunkManifestDataT()
        x._UnPack(chunkManifestData)
        return x

    # ChunkManifestDataT
    def _UnPack(self, chunkManifestData):
        if chunkManifestData is None:
            return
        self.id = chunkManifestData.Id()
        self.edgeId = chunkManifestData.EdgeId()
        self.startMeters = chunkManifestData.StartMeters()
        self.endMeters = chunkManifestData.EndMeters()
        self.contentHash = chunkManifestData.ContentHash()
        self.relativePath = chunkManifestData.RelativePath()
        if not chunkManifestData.ProbableBranchChunkIdsIsNone():
            self.probableBranchChunkIds = []
            for i in range(chunkManifestData.ProbableBranchChunkIdsLength()):
                self.probableBranchChunkIds.append(chunkManifestData.ProbableBranchChunkIds(i))

    # ChunkManifestDataT
    def Pack(self, builder):
        if self.id is not None:
            id = builder.CreateString(self.id)
        if self.edgeId is not None:
            edgeId = builder.CreateString(self.edgeId)
        if self.contentHash is not None:
            contentHash = builder.CreateString(self.contentHash)
        if self.relativePath is not None:
            relativePath = builder.CreateString(self.relativePath)
        if self.probableBranchChunkIds is not None:
            probableBranchChunkIdslist = []
            for i in range(len(self.probableBranchChunkIds)):
                probableBranchChunkIdslist.append(builder.CreateString(self.probableBranchChunkIds[i]))
            ChunkManifestDataStartProbableBranchChunkIdsVector(builder, len(self.probableBranchChunkIds))
            for i in reversed(range(len(self.probableBranchChunkIds))):
                builder.PrependUOffsetTRelative(probableBranchChunkIdslist[i])
            probableBranchChunkIds = builder.EndVector()
        ChunkManifestDataStart(builder)
        if self.id is not None:
            ChunkManifestDataAddId(builder, id)
        if self.edgeId is not None:
            ChunkManifestDataAddEdgeId(builder, edgeId)
        ChunkManifestDataAddStartMeters(builder, self.startMeters)
        ChunkManifestDataAddEndMeters(builder, self.endMeters)
        if self.contentHash is not None:
            ChunkManifestDataAddContentHash(builder, contentHash)
        if self.relativePath is not None:
            ChunkManifestDataAddRelativePath(builder, relativePath)
        if self.probableBranchChunkIds is not None:
            ChunkManifestDataAddProbableBranchChunkIds(builder, probableBranchChunkIds)
        chunkManifestData = ChunkManifestDataEnd(builder)
        return chunkManifestData
