# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Content

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ExitData(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ExitData()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsExitData(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def ExitDataBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x43\x42\x52\x47", size_prefixed=size_prefixed)

    # ExitData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ExitData
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ExitData
    def JunctionNodeId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ExitData
    def RampEdgeId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ExitData
    def RouteIdentityId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ExitData
    def Number(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ExitData
    def Suffix(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ExitData
    def Destinations(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # ExitData
    def DestinationsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ExitData
    def DestinationsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

    # ExitData
    def Services(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # ExitData
    def ServicesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ExitData
    def ServicesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        return o == 0

    # ExitData
    def Provenance(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from Cannonball.Content.SemanticProvenanceData import SemanticProvenanceData
            obj = SemanticProvenanceData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def ExitDataStart(builder):
    builder.StartObject(9)

def Start(builder):
    ExitDataStart(builder)

def ExitDataAddId(builder, id):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)

def AddId(builder, id):
    ExitDataAddId(builder, id)

def ExitDataAddJunctionNodeId(builder, junctionNodeId):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(junctionNodeId), 0)

def AddJunctionNodeId(builder, junctionNodeId):
    ExitDataAddJunctionNodeId(builder, junctionNodeId)

def ExitDataAddRampEdgeId(builder, rampEdgeId):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(rampEdgeId), 0)

def AddRampEdgeId(builder, rampEdgeId):
    ExitDataAddRampEdgeId(builder, rampEdgeId)

def ExitDataAddRouteIdentityId(builder, routeIdentityId):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(routeIdentityId), 0)

def AddRouteIdentityId(builder, routeIdentityId):
    ExitDataAddRouteIdentityId(builder, routeIdentityId)

def ExitDataAddNumber(builder, number):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(number), 0)

def AddNumber(builder, number):
    ExitDataAddNumber(builder, number)

def ExitDataAddSuffix(builder, suffix):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(suffix), 0)

def AddSuffix(builder, suffix):
    ExitDataAddSuffix(builder, suffix)

def ExitDataAddDestinations(builder, destinations):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(destinations), 0)

def AddDestinations(builder, destinations):
    ExitDataAddDestinations(builder, destinations)

def ExitDataStartDestinationsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartDestinationsVector(builder, numElems):
    return ExitDataStartDestinationsVector(builder, numElems)

def ExitDataAddServices(builder, services):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(services), 0)

def AddServices(builder, services):
    ExitDataAddServices(builder, services)

def ExitDataStartServicesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartServicesVector(builder, numElems):
    return ExitDataStartServicesVector(builder, numElems)

def ExitDataAddProvenance(builder, provenance):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(provenance), 0)

def AddProvenance(builder, provenance):
    ExitDataAddProvenance(builder, provenance)

def ExitDataEnd(builder):
    return builder.EndObject()

def End(builder):
    return ExitDataEnd(builder)

import Cannonball.Content.SemanticProvenanceData
try:
    from typing import List, Optional
except:
    pass

class ExitDataT(object):

    # ExitDataT
    def __init__(
        self,
        id = None,
        junctionNodeId = None,
        rampEdgeId = None,
        routeIdentityId = None,
        number = None,
        suffix = None,
        destinations = None,
        services = None,
        provenance = None,
    ):
        self.id = id  # type: Optional[str]
        self.junctionNodeId = junctionNodeId  # type: Optional[str]
        self.rampEdgeId = rampEdgeId  # type: Optional[str]
        self.routeIdentityId = routeIdentityId  # type: Optional[str]
        self.number = number  # type: Optional[str]
        self.suffix = suffix  # type: Optional[str]
        self.destinations = destinations  # type: Optional[List[Optional[str]]]
        self.services = services  # type: Optional[List[Optional[str]]]
        self.provenance = provenance  # type: Optional[Cannonball.Content.SemanticProvenanceData.SemanticProvenanceDataT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        exitData = ExitData()
        exitData.Init(buf, pos)
        return cls.InitFromObj(exitData)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, exitData):
        x = ExitDataT()
        x._UnPack(exitData)
        return x

    # ExitDataT
    def _UnPack(self, exitData):
        if exitData is None:
            return
        self.id = exitData.Id()
        self.junctionNodeId = exitData.JunctionNodeId()
        self.rampEdgeId = exitData.RampEdgeId()
        self.routeIdentityId = exitData.RouteIdentityId()
        self.number = exitData.Number()
        self.suffix = exitData.Suffix()
        if not exitData.DestinationsIsNone():
            self.destinations = []
            for i in range(exitData.DestinationsLength()):
                self.destinations.append(exitData.Destinations(i))
        if not exitData.ServicesIsNone():
            self.services = []
            for i in range(exitData.ServicesLength()):
                self.services.append(exitData.Services(i))
        if exitData.Provenance() is not None:
            self.provenance = Cannonball.Content.SemanticProvenanceData.SemanticProvenanceDataT.InitFromObj(exitData.Provenance())

    # ExitDataT
    def Pack(self, builder):
        if self.id is not None:
            id = builder.CreateString(self.id)
        if self.junctionNodeId is not None:
            junctionNodeId = builder.CreateString(self.junctionNodeId)
        if self.rampEdgeId is not None:
            rampEdgeId = builder.CreateString(self.rampEdgeId)
        if self.routeIdentityId is not None:
            routeIdentityId = builder.CreateString(self.routeIdentityId)
        if self.number is not None:
            number = builder.CreateString(self.number)
        if self.suffix is not None:
            suffix = builder.CreateString(self.suffix)
        if self.destinations is not None:
            destinationslist = []
            for i in range(len(self.destinations)):
                destinationslist.append(builder.CreateString(self.destinations[i]))
            ExitDataStartDestinationsVector(builder, len(self.destinations))
            for i in reversed(range(len(self.destinations))):
                builder.PrependUOffsetTRelative(destinationslist[i])
            destinations = builder.EndVector()
        if self.services is not None:
            serviceslist = []
            for i in range(len(self.services)):
                serviceslist.append(builder.CreateString(self.services[i]))
            ExitDataStartServicesVector(builder, len(self.services))
            for i in reversed(range(len(self.services))):
                builder.PrependUOffsetTRelative(serviceslist[i])
            services = builder.EndVector()
        if self.provenance is not None:
            provenance = self.provenance.Pack(builder)
        ExitDataStart(builder)
        if self.id is not None:
            ExitDataAddId(builder, id)
        if self.junctionNodeId is not None:
            ExitDataAddJunctionNodeId(builder, junctionNodeId)
        if self.rampEdgeId is not None:
            ExitDataAddRampEdgeId(builder, rampEdgeId)
        if self.routeIdentityId is not None:
            ExitDataAddRouteIdentityId(builder, routeIdentityId)
        if self.number is not None:
            ExitDataAddNumber(builder, number)
        if self.suffix is not None:
            ExitDataAddSuffix(builder, suffix)
        if self.destinations is not None:
            ExitDataAddDestinations(builder, destinations)
        if self.services is not None:
            ExitDataAddServices(builder, services)
        if self.provenance is not None:
            ExitDataAddProvenance(builder, provenance)
        exitData = ExitDataEnd(builder)
        return exitData
