# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Content

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class JunctionConnectorData(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = JunctionConnectorData()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsJunctionConnectorData(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def JunctionConnectorDataBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x43\x42\x52\x47", size_prefixed=size_prefixed)

    # JunctionConnectorData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # JunctionConnectorData
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # JunctionConnectorData
    def JunctionNodeId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # JunctionConnectorData
    def FromEdgeId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # JunctionConnectorData
    def FromLaneId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # JunctionConnectorData
    def ToEdgeId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # JunctionConnectorData
    def ToLaneId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # JunctionConnectorData
    def Movement(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # JunctionConnectorData
    def Provenance(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from Cannonball.Content.SemanticProvenanceData import SemanticProvenanceData
            obj = SemanticProvenanceData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def JunctionConnectorDataStart(builder):
    builder.StartObject(8)

def Start(builder):
    JunctionConnectorDataStart(builder)

def JunctionConnectorDataAddId(builder, id):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)

def AddId(builder, id):
    JunctionConnectorDataAddId(builder, id)

def JunctionConnectorDataAddJunctionNodeId(builder, junctionNodeId):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(junctionNodeId), 0)

def AddJunctionNodeId(builder, junctionNodeId):
    JunctionConnectorDataAddJunctionNodeId(builder, junctionNodeId)

def JunctionConnectorDataAddFromEdgeId(builder, fromEdgeId):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(fromEdgeId), 0)

def AddFromEdgeId(builder, fromEdgeId):
    JunctionConnectorDataAddFromEdgeId(builder, fromEdgeId)

def JunctionConnectorDataAddFromLaneId(builder, fromLaneId):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(fromLaneId), 0)

def AddFromLaneId(builder, fromLaneId):
    JunctionConnectorDataAddFromLaneId(builder, fromLaneId)

def JunctionConnectorDataAddToEdgeId(builder, toEdgeId):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(toEdgeId), 0)

def AddToEdgeId(builder, toEdgeId):
    JunctionConnectorDataAddToEdgeId(builder, toEdgeId)

def JunctionConnectorDataAddToLaneId(builder, toLaneId):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(toLaneId), 0)

def AddToLaneId(builder, toLaneId):
    JunctionConnectorDataAddToLaneId(builder, toLaneId)

def JunctionConnectorDataAddMovement(builder, movement):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(movement), 0)

def AddMovement(builder, movement):
    JunctionConnectorDataAddMovement(builder, movement)

def JunctionConnectorDataAddProvenance(builder, provenance):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(provenance), 0)

def AddProvenance(builder, provenance):
    JunctionConnectorDataAddProvenance(builder, provenance)

def JunctionConnectorDataEnd(builder):
    return builder.EndObject()

def End(builder):
    return JunctionConnectorDataEnd(builder)

import Cannonball.Content.SemanticProvenanceData
try:
    from typing import Optional
except:
    pass

class JunctionConnectorDataT(object):

    # JunctionConnectorDataT
    def __init__(
        self,
        id = None,
        junctionNodeId = None,
        fromEdgeId = None,
        fromLaneId = None,
        toEdgeId = None,
        toLaneId = None,
        movement = None,
        provenance = None,
    ):
        self.id = id  # type: Optional[str]
        self.junctionNodeId = junctionNodeId  # type: Optional[str]
        self.fromEdgeId = fromEdgeId  # type: Optional[str]
        self.fromLaneId = fromLaneId  # type: Optional[str]
        self.toEdgeId = toEdgeId  # type: Optional[str]
        self.toLaneId = toLaneId  # type: Optional[str]
        self.movement = movement  # type: Optional[str]
        self.provenance = provenance  # type: Optional[Cannonball.Content.SemanticProvenanceData.SemanticProvenanceDataT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        junctionConnectorData = JunctionConnectorData()
        junctionConnectorData.Init(buf, pos)
        return cls.InitFromObj(junctionConnectorData)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, junctionConnectorData):
        x = JunctionConnectorDataT()
        x._UnPack(junctionConnectorData)
        return x

    # JunctionConnectorDataT
    def _UnPack(self, junctionConnectorData):
        if junctionConnectorData is None:
            return
        self.id = junctionConnectorData.Id()
        self.junctionNodeId = junctionConnectorData.JunctionNodeId()
        self.fromEdgeId = junctionConnectorData.FromEdgeId()
        self.fromLaneId = junctionConnectorData.FromLaneId()
        self.toEdgeId = junctionConnectorData.ToEdgeId()
        self.toLaneId = junctionConnectorData.ToLaneId()
        self.movement = junctionConnectorData.Movement()
        if junctionConnectorData.Provenance() is not None:
            self.provenance = Cannonball.Content.SemanticProvenanceData.SemanticProvenanceDataT.InitFromObj(junctionConnectorData.Provenance())

    # JunctionConnectorDataT
    def Pack(self, builder):
        if self.id is not None:
            id = builder.CreateString(self.id)
        if self.junctionNodeId is not None:
            junctionNodeId = builder.CreateString(self.junctionNodeId)
        if self.fromEdgeId is not None:
            fromEdgeId = builder.CreateString(self.fromEdgeId)
        if self.fromLaneId is not None:
            fromLaneId = builder.CreateString(self.fromLaneId)
        if self.toEdgeId is not None:
            toEdgeId = builder.CreateString(self.toEdgeId)
        if self.toLaneId is not None:
            toLaneId = builder.CreateString(self.toLaneId)
        if self.movement is not None:
            movement = builder.CreateString(self.movement)
        if self.provenance is not None:
            provenance = self.provenance.Pack(builder)
        JunctionConnectorDataStart(builder)
        if self.id is not None:
            JunctionConnectorDataAddId(builder, id)
        if self.junctionNodeId is not None:
            JunctionConnectorDataAddJunctionNodeId(builder, junctionNodeId)
        if self.fromEdgeId is not None:
            JunctionConnectorDataAddFromEdgeId(builder, fromEdgeId)
        if self.fromLaneId is not None:
            JunctionConnectorDataAddFromLaneId(builder, fromLaneId)
        if self.toEdgeId is not None:
            JunctionConnectorDataAddToEdgeId(builder, toEdgeId)
        if self.toLaneId is not None:
            JunctionConnectorDataAddToLaneId(builder, toLaneId)
        if self.movement is not None:
            JunctionConnectorDataAddMovement(builder, movement)
        if self.provenance is not None:
            JunctionConnectorDataAddProvenance(builder, provenance)
        junctionConnectorData = JunctionConnectorDataEnd(builder)
        return junctionConnectorData
