# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Content

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class LaneSectionData(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = LaneSectionData()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsLaneSectionData(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def LaneSectionDataBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x43\x42\x52\x47", size_prefixed=size_prefixed)

    # LaneSectionData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # LaneSectionData
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LaneSectionData
    def EdgeId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LaneSectionData
    def StartMeters(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # LaneSectionData
    def EndMeters(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # LaneSectionData
    def Lanes(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Cannonball.Content.RouteLaneData import RouteLaneData
            obj = RouteLaneData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # LaneSectionData
    def LanesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # LaneSectionData
    def LanesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # LaneSectionData
    def LeftShoulder(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from Cannonball.Content.RouteShoulderData import RouteShoulderData
            obj = RouteShoulderData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # LaneSectionData
    def RightShoulder(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from Cannonball.Content.RouteShoulderData import RouteShoulderData
            obj = RouteShoulderData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # LaneSectionData
    def SignedDirection(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LaneSectionData
    def Provenance(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from Cannonball.Content.SemanticProvenanceData import SemanticProvenanceData
            obj = SemanticProvenanceData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def LaneSectionDataStart(builder):
    builder.StartObject(9)

def Start(builder):
    LaneSectionDataStart(builder)

def LaneSectionDataAddId(builder, id):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)

def AddId(builder, id):
    LaneSectionDataAddId(builder, id)

def LaneSectionDataAddEdgeId(builder, edgeId):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(edgeId), 0)

def AddEdgeId(builder, edgeId):
    LaneSectionDataAddEdgeId(builder, edgeId)

def LaneSectionDataAddStartMeters(builder, startMeters):
    builder.PrependFloat64Slot(2, startMeters, 0.0)

def AddStartMeters(builder, startMeters):
    LaneSectionDataAddStartMeters(builder, startMeters)

def LaneSectionDataAddEndMeters(builder, endMeters):
    builder.PrependFloat64Slot(3, endMeters, 0.0)

def AddEndMeters(builder, endMeters):
    LaneSectionDataAddEndMeters(builder, endMeters)

def LaneSectionDataAddLanes(builder, lanes):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(lanes), 0)

def AddLanes(builder, lanes):
    LaneSectionDataAddLanes(builder, lanes)

def LaneSectionDataStartLanesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartLanesVector(builder, numElems):
    return LaneSectionDataStartLanesVector(builder, numElems)

def LaneSectionDataAddLeftShoulder(builder, leftShoulder):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(leftShoulder), 0)

def AddLeftShoulder(builder, leftShoulder):
    LaneSectionDataAddLeftShoulder(builder, leftShoulder)

def LaneSectionDataAddRightShoulder(builder, rightShoulder):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(rightShoulder), 0)

def AddRightShoulder(builder, rightShoulder):
    LaneSectionDataAddRightShoulder(builder, rightShoulder)

def LaneSectionDataAddSignedDirection(builder, signedDirection):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(signedDirection), 0)

def AddSignedDirection(builder, signedDirection):
    LaneSectionDataAddSignedDirection(builder, signedDirection)

def LaneSectionDataAddProvenance(builder, provenance):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(provenance), 0)

def AddProvenance(builder, provenance):
    LaneSectionDataAddProvenance(builder, provenance)

def LaneSectionDataEnd(builder):
    return builder.EndObject()

def End(builder):
    return LaneSectionDataEnd(builder)

import Cannonball.Content.RouteLaneData
import Cannonball.Content.RouteShoulderData
import Cannonball.Content.SemanticProvenanceData
try:
    from typing import List, Optional
except:
    pass

class LaneSectionDataT(object):

    # LaneSectionDataT
    def __init__(
        self,
        id = None,
        edgeId = None,
        startMeters = 0.0,
        endMeters = 0.0,
        lanes = None,
        leftShoulder = None,
        rightShoulder = None,
        signedDirection = None,
        provenance = None,
    ):
        self.id = id  # type: Optional[str]
        self.edgeId = edgeId  # type: Optional[str]
        self.startMeters = startMeters  # type: float
        self.endMeters = endMeters  # type: float
        self.lanes = lanes  # type: Optional[List[Cannonball.Content.RouteLaneData.RouteLaneDataT]]
        self.leftShoulder = leftShoulder  # type: Optional[Cannonball.Content.RouteShoulderData.RouteShoulderDataT]
        self.rightShoulder = rightShoulder  # type: Optional[Cannonball.Content.RouteShoulderData.RouteShoulderDataT]
        self.signedDirection = signedDirection  # type: Optional[str]
        self.provenance = provenance  # type: Optional[Cannonball.Content.SemanticProvenanceData.SemanticProvenanceDataT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        laneSectionData = LaneSectionData()
        laneSectionData.Init(buf, pos)
        return cls.InitFromObj(laneSectionData)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, laneSectionData):
        x = LaneSectionDataT()
        x._UnPack(laneSectionData)
        return x

    # LaneSectionDataT
    def _UnPack(self, laneSectionData):
        if laneSectionData is None:
            return
        self.id = laneSectionData.Id()
        self.edgeId = laneSectionData.EdgeId()
        self.startMeters = laneSectionData.StartMeters()
        self.endMeters = laneSectionData.EndMeters()
        if not laneSectionData.LanesIsNone():
            self.lanes = []
            for i in range(laneSectionData.LanesLength()):
                if laneSectionData.Lanes(i) is None:
                    self.lanes.append(None)
                else:
                    routeLaneData_ = Cannonball.Content.RouteLaneData.RouteLaneDataT.InitFromObj(laneSectionData.Lanes(i))
                    self.lanes.append(routeLaneData_)
        if laneSectionData.LeftShoulder() is not None:
            self.leftShoulder = Cannonball.Content.RouteShoulderData.RouteShoulderDataT.InitFromObj(laneSectionData.LeftShoulder())
        if laneSectionData.RightShoulder() is not None:
            self.rightShoulder = Cannonball.Content.RouteShoulderData.RouteShoulderDataT.InitFromObj(laneSectionData.RightShoulder())
        self.signedDirection = laneSectionData.SignedDirection()
        if laneSectionData.Provenance() is not None:
            self.provenance = Cannonball.Content.SemanticProvenanceData.SemanticProvenanceDataT.InitFromObj(laneSectionData.Provenance())

    # LaneSectionDataT
    def Pack(self, builder):
        if self.id is not None:
            id = builder.CreateString(self.id)
        if self.edgeId is not None:
            edgeId = builder.CreateString(self.edgeId)
        if self.lanes is not None:
            laneslist = []
            for i in range(len(self.lanes)):
                laneslist.append(self.lanes[i].Pack(builder))
            LaneSectionDataStartLanesVector(builder, len(self.lanes))
            for i in reversed(range(len(self.lanes))):
                builder.PrependUOffsetTRelative(laneslist[i])
            lanes = builder.EndVector()
        if self.leftShoulder is not None:
            leftShoulder = self.leftShoulder.Pack(builder)
        if self.rightShoulder is not None:
            rightShoulder = self.rightShoulder.Pack(builder)
        if self.signedDirection is not None:
            signedDirection = builder.CreateString(self.signedDirection)
        if self.provenance is not None:
            provenance = self.provenance.Pack(builder)
        LaneSectionDataStart(builder)
        if self.id is not None:
            LaneSectionDataAddId(builder, id)
        if self.edgeId is not None:
            LaneSectionDataAddEdgeId(builder, edgeId)
        LaneSectionDataAddStartMeters(builder, self.startMeters)
        LaneSectionDataAddEndMeters(builder, self.endMeters)
        if self.lanes is not None:
            LaneSectionDataAddLanes(builder, lanes)
        if self.leftShoulder is not None:
            LaneSectionDataAddLeftShoulder(builder, leftShoulder)
        if self.rightShoulder is not None:
            LaneSectionDataAddRightShoulder(builder, rightShoulder)
        if self.signedDirection is not None:
            LaneSectionDataAddSignedDirection(builder, signedDirection)
        if self.provenance is not None:
            LaneSectionDataAddProvenance(builder, provenance)
        laneSectionData = LaneSectionDataEnd(builder)
        return laneSectionData
