# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Content

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class MilepointAnchorData(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MilepointAnchorData()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMilepointAnchorData(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def MilepointAnchorDataBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x43\x42\x52\x47", size_prefixed=size_prefixed)

    # MilepointAnchorData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MilepointAnchorData
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MilepointAnchorData
    def RouteIdentityId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MilepointAnchorData
    def EdgeId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MilepointAnchorData
    def DistanceMeters(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # MilepointAnchorData
    def ValueMiles(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # MilepointAnchorData
    def Jurisdiction(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MilepointAnchorData
    def SignedDirection(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MilepointAnchorData
    def Provenance(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from Cannonball.Content.SemanticProvenanceData import SemanticProvenanceData
            obj = SemanticProvenanceData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def MilepointAnchorDataStart(builder):
    builder.StartObject(8)

def Start(builder):
    MilepointAnchorDataStart(builder)

def MilepointAnchorDataAddId(builder, id):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)

def AddId(builder, id):
    MilepointAnchorDataAddId(builder, id)

def MilepointAnchorDataAddRouteIdentityId(builder, routeIdentityId):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(routeIdentityId), 0)

def AddRouteIdentityId(builder, routeIdentityId):
    MilepointAnchorDataAddRouteIdentityId(builder, routeIdentityId)

def MilepointAnchorDataAddEdgeId(builder, edgeId):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(edgeId), 0)

def AddEdgeId(builder, edgeId):
    MilepointAnchorDataAddEdgeId(builder, edgeId)

def MilepointAnchorDataAddDistanceMeters(builder, distanceMeters):
    builder.PrependFloat64Slot(3, distanceMeters, 0.0)

def AddDistanceMeters(builder, distanceMeters):
    MilepointAnchorDataAddDistanceMeters(builder, distanceMeters)

def MilepointAnchorDataAddValueMiles(builder, valueMiles):
    builder.PrependFloat64Slot(4, valueMiles, 0.0)

def AddValueMiles(builder, valueMiles):
    MilepointAnchorDataAddValueMiles(builder, valueMiles)

def MilepointAnchorDataAddJurisdiction(builder, jurisdiction):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(jurisdiction), 0)

def AddJurisdiction(builder, jurisdiction):
    MilepointAnchorDataAddJurisdiction(builder, jurisdiction)

def MilepointAnchorDataAddSignedDirection(builder, signedDirection):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(signedDirection), 0)

def AddSignedDirection(builder, signedDirection):
    MilepointAnchorDataAddSignedDirection(builder, signedDirection)

def MilepointAnchorDataAddProvenance(builder, provenance):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(provenance), 0)

def AddProvenance(builder, provenance):
    MilepointAnchorDataAddProvenance(builder, provenance)

def MilepointAnchorDataEnd(builder):
    return builder.EndObject()

def End(builder):
    return MilepointAnchorDataEnd(builder)

import Cannonball.Content.SemanticProvenanceData
try:
    from typing import Optional
except:
    pass

class MilepointAnchorDataT(object):

    # MilepointAnchorDataT
    def __init__(
        self,
        id = None,
        routeIdentityId = None,
        edgeId = None,
        distanceMeters = 0.0,
        valueMiles = 0.0,
        jurisdiction = None,
        signedDirection = None,
        provenance = None,
    ):
        self.id = id  # type: Optional[str]
        self.routeIdentityId = routeIdentityId  # type: Optional[str]
        self.edgeId = edgeId  # type: Optional[str]
        self.distanceMeters = distanceMeters  # type: float
        self.valueMiles = valueMiles  # type: float
        self.jurisdiction = jurisdiction  # type: Optional[str]
        self.signedDirection = signedDirection  # type: Optional[str]
        self.provenance = provenance  # type: Optional[Cannonball.Content.SemanticProvenanceData.SemanticProvenanceDataT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        milepointAnchorData = MilepointAnchorData()
        milepointAnchorData.Init(buf, pos)
        return cls.InitFromObj(milepointAnchorData)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, milepointAnchorData):
        x = MilepointAnchorDataT()
        x._UnPack(milepointAnchorData)
        return x

    # MilepointAnchorDataT
    def _UnPack(self, milepointAnchorData):
        if milepointAnchorData is None:
            return
        self.id = milepointAnchorData.Id()
        self.routeIdentityId = milepointAnchorData.RouteIdentityId()
        self.edgeId = milepointAnchorData.EdgeId()
        self.distanceMeters = milepointAnchorData.DistanceMeters()
        self.valueMiles = milepointAnchorData.ValueMiles()
        self.jurisdiction = milepointAnchorData.Jurisdiction()
        self.signedDirection = milepointAnchorData.SignedDirection()
        if milepointAnchorData.Provenance() is not None:
            self.provenance = Cannonball.Content.SemanticProvenanceData.SemanticProvenanceDataT.InitFromObj(milepointAnchorData.Provenance())

    # MilepointAnchorDataT
    def Pack(self, builder):
        if self.id is not None:
            id = builder.CreateString(self.id)
        if self.routeIdentityId is not None:
            routeIdentityId = builder.CreateString(self.routeIdentityId)
        if self.edgeId is not None:
            edgeId = builder.CreateString(self.edgeId)
        if self.jurisdiction is not None:
            jurisdiction = builder.CreateString(self.jurisdiction)
        if self.signedDirection is not None:
            signedDirection = builder.CreateString(self.signedDirection)
        if self.provenance is not None:
            provenance = self.provenance.Pack(builder)
        MilepointAnchorDataStart(builder)
        if self.id is not None:
            MilepointAnchorDataAddId(builder, id)
        if self.routeIdentityId is not None:
            MilepointAnchorDataAddRouteIdentityId(builder, routeIdentityId)
        if self.edgeId is not None:
            MilepointAnchorDataAddEdgeId(builder, edgeId)
        MilepointAnchorDataAddDistanceMeters(builder, self.distanceMeters)
        MilepointAnchorDataAddValueMiles(builder, self.valueMiles)
        if self.jurisdiction is not None:
            MilepointAnchorDataAddJurisdiction(builder, jurisdiction)
        if self.signedDirection is not None:
            MilepointAnchorDataAddSignedDirection(builder, signedDirection)
        if self.provenance is not None:
            MilepointAnchorDataAddProvenance(builder, provenance)
        milepointAnchorData = MilepointAnchorDataEnd(builder)
        return milepointAnchorData
