# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Content

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RoadsideMarkerData(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RoadsideMarkerData()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRoadsideMarkerData(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def RoadsideMarkerDataBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x43\x42\x52\x47", size_prefixed=size_prefixed)

    # RoadsideMarkerData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RoadsideMarkerData
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RoadsideMarkerData
    def Kind(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RoadsideMarkerData
    def RouteIdentityId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RoadsideMarkerData
    def EdgeId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RoadsideMarkerData
    def DistanceMeters(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # RoadsideMarkerData
    def DisplayText(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RoadsideMarkerData
    def Provenance(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from Cannonball.Content.SemanticProvenanceData import SemanticProvenanceData
            obj = SemanticProvenanceData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def RoadsideMarkerDataStart(builder):
    builder.StartObject(7)

def Start(builder):
    RoadsideMarkerDataStart(builder)

def RoadsideMarkerDataAddId(builder, id):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)

def AddId(builder, id):
    RoadsideMarkerDataAddId(builder, id)

def RoadsideMarkerDataAddKind(builder, kind):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(kind), 0)

def AddKind(builder, kind):
    RoadsideMarkerDataAddKind(builder, kind)

def RoadsideMarkerDataAddRouteIdentityId(builder, routeIdentityId):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(routeIdentityId), 0)

def AddRouteIdentityId(builder, routeIdentityId):
    RoadsideMarkerDataAddRouteIdentityId(builder, routeIdentityId)

def RoadsideMarkerDataAddEdgeId(builder, edgeId):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(edgeId), 0)

def AddEdgeId(builder, edgeId):
    RoadsideMarkerDataAddEdgeId(builder, edgeId)

def RoadsideMarkerDataAddDistanceMeters(builder, distanceMeters):
    builder.PrependFloat64Slot(4, distanceMeters, 0.0)

def AddDistanceMeters(builder, distanceMeters):
    RoadsideMarkerDataAddDistanceMeters(builder, distanceMeters)

def RoadsideMarkerDataAddDisplayText(builder, displayText):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(displayText), 0)

def AddDisplayText(builder, displayText):
    RoadsideMarkerDataAddDisplayText(builder, displayText)

def RoadsideMarkerDataAddProvenance(builder, provenance):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(provenance), 0)

def AddProvenance(builder, provenance):
    RoadsideMarkerDataAddProvenance(builder, provenance)

def RoadsideMarkerDataEnd(builder):
    return builder.EndObject()

def End(builder):
    return RoadsideMarkerDataEnd(builder)

import Cannonball.Content.SemanticProvenanceData
try:
    from typing import Optional
except:
    pass

class RoadsideMarkerDataT(object):

    # RoadsideMarkerDataT
    def __init__(
        self,
        id = None,
        kind = None,
        routeIdentityId = None,
        edgeId = None,
        distanceMeters = 0.0,
        displayText = None,
        provenance = None,
    ):
        self.id = id  # type: Optional[str]
        self.kind = kind  # type: Optional[str]
        self.routeIdentityId = routeIdentityId  # type: Optional[str]
        self.edgeId = edgeId  # type: Optional[str]
        self.distanceMeters = distanceMeters  # type: float
        self.displayText = displayText  # type: Optional[str]
        self.provenance = provenance  # type: Optional[Cannonball.Content.SemanticProvenanceData.SemanticProvenanceDataT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        roadsideMarkerData = RoadsideMarkerData()
        roadsideMarkerData.Init(buf, pos)
        return cls.InitFromObj(roadsideMarkerData)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, roadsideMarkerData):
        x = RoadsideMarkerDataT()
        x._UnPack(roadsideMarkerData)
        return x

    # RoadsideMarkerDataT
    def _UnPack(self, roadsideMarkerData):
        if roadsideMarkerData is None:
            return
        self.id = roadsideMarkerData.Id()
        self.kind = roadsideMarkerData.Kind()
        self.routeIdentityId = roadsideMarkerData.RouteIdentityId()
        self.edgeId = roadsideMarkerData.EdgeId()
        self.distanceMeters = roadsideMarkerData.DistanceMeters()
        self.displayText = roadsideMarkerData.DisplayText()
        if roadsideMarkerData.Provenance() is not None:
            self.provenance = Cannonball.Content.SemanticProvenanceData.SemanticProvenanceDataT.InitFromObj(roadsideMarkerData.Provenance())

    # RoadsideMarkerDataT
    def Pack(self, builder):
        if self.id is not None:
            id = builder.CreateString(self.id)
        if self.kind is not None:
            kind = builder.CreateString(self.kind)
        if self.routeIdentityId is not None:
            routeIdentityId = builder.CreateString(self.routeIdentityId)
        if self.edgeId is not None:
            edgeId = builder.CreateString(self.edgeId)
        if self.displayText is not None:
            displayText = builder.CreateString(self.displayText)
        if self.provenance is not None:
            provenance = self.provenance.Pack(builder)
        RoadsideMarkerDataStart(builder)
        if self.id is not None:
            RoadsideMarkerDataAddId(builder, id)
        if self.kind is not None:
            RoadsideMarkerDataAddKind(builder, kind)
        if self.routeIdentityId is not None:
            RoadsideMarkerDataAddRouteIdentityId(builder, routeIdentityId)
        if self.edgeId is not None:
            RoadsideMarkerDataAddEdgeId(builder, edgeId)
        RoadsideMarkerDataAddDistanceMeters(builder, self.distanceMeters)
        if self.displayText is not None:
            RoadsideMarkerDataAddDisplayText(builder, displayText)
        if self.provenance is not None:
            RoadsideMarkerDataAddProvenance(builder, provenance)
        roadsideMarkerData = RoadsideMarkerDataEnd(builder)
        return roadsideMarkerData
