# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Content

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RouteShoulderData(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RouteShoulderData()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRouteShoulderData(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def RouteShoulderDataBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x43\x42\x52\x47", size_prefixed=size_prefixed)

    # RouteShoulderData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RouteShoulderData
    def WidthMeters(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # RouteShoulderData
    def Kind(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def RouteShoulderDataStart(builder):
    builder.StartObject(2)

def Start(builder):
    RouteShoulderDataStart(builder)

def RouteShoulderDataAddWidthMeters(builder, widthMeters):
    builder.PrependFloat32Slot(0, widthMeters, 0.0)

def AddWidthMeters(builder, widthMeters):
    RouteShoulderDataAddWidthMeters(builder, widthMeters)

def RouteShoulderDataAddKind(builder, kind):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(kind), 0)

def AddKind(builder, kind):
    RouteShoulderDataAddKind(builder, kind)

def RouteShoulderDataEnd(builder):
    return builder.EndObject()

def End(builder):
    return RouteShoulderDataEnd(builder)


class RouteShoulderDataT(object):

    # RouteShoulderDataT
    def __init__(
        self,
        widthMeters = 0.0,
        kind = None,
    ):
        self.widthMeters = widthMeters  # type: float
        self.kind = kind  # type: Optional[str]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        routeShoulderData = RouteShoulderData()
        routeShoulderData.Init(buf, pos)
        return cls.InitFromObj(routeShoulderData)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, routeShoulderData):
        x = RouteShoulderDataT()
        x._UnPack(routeShoulderData)
        return x

    # RouteShoulderDataT
    def _UnPack(self, routeShoulderData):
        if routeShoulderData is None:
            return
        self.widthMeters = routeShoulderData.WidthMeters()
        self.kind = routeShoulderData.Kind()

    # RouteShoulderDataT
    def Pack(self, builder):
        if self.kind is not None:
            kind = builder.CreateString(self.kind)
        RouteShoulderDataStart(builder)
        RouteShoulderDataAddWidthMeters(builder, self.widthMeters)
        if self.kind is not None:
            RouteShoulderDataAddKind(builder, kind)
        routeShoulderData = RouteShoulderDataEnd(builder)
        return routeShoulderData
