# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Content

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RouteGraphBuffer(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RouteGraphBuffer()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRouteGraphBuffer(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def RouteGraphBufferBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x43\x42\x52\x47", size_prefixed=size_prefixed)

    # RouteGraphBuffer
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RouteGraphBuffer
    def SchemaVersion(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # RouteGraphBuffer
    def ContentVersion(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RouteGraphBuffer
    def Nodes(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Cannonball.Content.RouteNodeData import RouteNodeData
            obj = RouteNodeData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RouteGraphBuffer
    def NodesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RouteGraphBuffer
    def NodesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # RouteGraphBuffer
    def Edges(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Cannonball.Content.RouteEdgeData import RouteEdgeData
            obj = RouteEdgeData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RouteGraphBuffer
    def EdgesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RouteGraphBuffer
    def EdgesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # RouteGraphBuffer
    def Chunks(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Cannonball.Content.ChunkManifestData import ChunkManifestData
            obj = ChunkManifestData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RouteGraphBuffer
    def ChunksLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RouteGraphBuffer
    def ChunksIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # RouteGraphBuffer
    def Provenance(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from Cannonball.Content.SourceProvenanceData import SourceProvenanceData
            obj = SourceProvenanceData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RouteGraphBuffer
    def SpatialReference(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from Cannonball.Content.SpatialReferenceData import SpatialReferenceData
            obj = SpatialReferenceData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def RouteGraphBufferStart(builder):
    builder.StartObject(7)

def Start(builder):
    RouteGraphBufferStart(builder)

def RouteGraphBufferAddSchemaVersion(builder, schemaVersion):
    builder.PrependUint32Slot(0, schemaVersion, 0)

def AddSchemaVersion(builder, schemaVersion):
    RouteGraphBufferAddSchemaVersion(builder, schemaVersion)

def RouteGraphBufferAddContentVersion(builder, contentVersion):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(contentVersion), 0)

def AddContentVersion(builder, contentVersion):
    RouteGraphBufferAddContentVersion(builder, contentVersion)

def RouteGraphBufferAddNodes(builder, nodes):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(nodes), 0)

def AddNodes(builder, nodes):
    RouteGraphBufferAddNodes(builder, nodes)

def RouteGraphBufferStartNodesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartNodesVector(builder, numElems):
    return RouteGraphBufferStartNodesVector(builder, numElems)

def RouteGraphBufferAddEdges(builder, edges):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(edges), 0)

def AddEdges(builder, edges):
    RouteGraphBufferAddEdges(builder, edges)

def RouteGraphBufferStartEdgesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartEdgesVector(builder, numElems):
    return RouteGraphBufferStartEdgesVector(builder, numElems)

def RouteGraphBufferAddChunks(builder, chunks):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(chunks), 0)

def AddChunks(builder, chunks):
    RouteGraphBufferAddChunks(builder, chunks)

def RouteGraphBufferStartChunksVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartChunksVector(builder, numElems):
    return RouteGraphBufferStartChunksVector(builder, numElems)

def RouteGraphBufferAddProvenance(builder, provenance):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(provenance), 0)

def AddProvenance(builder, provenance):
    RouteGraphBufferAddProvenance(builder, provenance)

def RouteGraphBufferAddSpatialReference(builder, spatialReference):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(spatialReference), 0)

def AddSpatialReference(builder, spatialReference):
    RouteGraphBufferAddSpatialReference(builder, spatialReference)

def RouteGraphBufferEnd(builder):
    return builder.EndObject()

def End(builder):
    return RouteGraphBufferEnd(builder)

import Cannonball.Content.ChunkManifestData
import Cannonball.Content.RouteEdgeData
import Cannonball.Content.RouteNodeData
import Cannonball.Content.SourceProvenanceData
import Cannonball.Content.SpatialReferenceData
try:
    from typing import List, Optional
except:
    pass

class RouteGraphBufferT(object):

    # RouteGraphBufferT
    def __init__(
        self,
        schemaVersion = 0,
        contentVersion = None,
        nodes = None,
        edges = None,
        chunks = None,
        provenance = None,
        spatialReference = None,
    ):
        self.schemaVersion = schemaVersion  # type: int
        self.contentVersion = contentVersion  # type: Optional[str]
        self.nodes = nodes  # type: Optional[List[Cannonball.Content.RouteNodeData.RouteNodeDataT]]
        self.edges = edges  # type: Optional[List[Cannonball.Content.RouteEdgeData.RouteEdgeDataT]]
        self.chunks = chunks  # type: Optional[List[Cannonball.Content.ChunkManifestData.ChunkManifestDataT]]
        self.provenance = provenance  # type: Optional[Cannonball.Content.SourceProvenanceData.SourceProvenanceDataT]
        self.spatialReference = spatialReference  # type: Optional[Cannonball.Content.SpatialReferenceData.SpatialReferenceDataT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        routeGraphBuffer = RouteGraphBuffer()
        routeGraphBuffer.Init(buf, pos)
        return cls.InitFromObj(routeGraphBuffer)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, routeGraphBuffer):
        x = RouteGraphBufferT()
        x._UnPack(routeGraphBuffer)
        return x

    # RouteGraphBufferT
    def _UnPack(self, routeGraphBuffer):
        if routeGraphBuffer is None:
            return
        self.schemaVersion = routeGraphBuffer.SchemaVersion()
        self.contentVersion = routeGraphBuffer.ContentVersion()
        if not routeGraphBuffer.NodesIsNone():
            self.nodes = []
            for i in range(routeGraphBuffer.NodesLength()):
                if routeGraphBuffer.Nodes(i) is None:
                    self.nodes.append(None)
                else:
                    routeNodeData_ = Cannonball.Content.RouteNodeData.RouteNodeDataT.InitFromObj(routeGraphBuffer.Nodes(i))
                    self.nodes.append(routeNodeData_)
        if not routeGraphBuffer.EdgesIsNone():
            self.edges = []
            for i in range(routeGraphBuffer.EdgesLength()):
                if routeGraphBuffer.Edges(i) is None:
                    self.edges.append(None)
                else:
                    routeEdgeData_ = Cannonball.Content.RouteEdgeData.RouteEdgeDataT.InitFromObj(routeGraphBuffer.Edges(i))
                    self.edges.append(routeEdgeData_)
        if not routeGraphBuffer.ChunksIsNone():
            self.chunks = []
            for i in range(routeGraphBuffer.ChunksLength()):
                if routeGraphBuffer.Chunks(i) is None:
                    self.chunks.append(None)
                else:
                    chunkManifestData_ = Cannonball.Content.ChunkManifestData.ChunkManifestDataT.InitFromObj(routeGraphBuffer.Chunks(i))
                    self.chunks.append(chunkManifestData_)
        if routeGraphBuffer.Provenance() is not None:
            self.provenance = Cannonball.Content.SourceProvenanceData.SourceProvenanceDataT.InitFromObj(routeGraphBuffer.Provenance())
        if routeGraphBuffer.SpatialReference() is not None:
            self.spatialReference = Cannonball.Content.SpatialReferenceData.SpatialReferenceDataT.InitFromObj(routeGraphBuffer.SpatialReference())

    # RouteGraphBufferT
    def Pack(self, builder):
        if self.contentVersion is not None:
            contentVersion = builder.CreateString(self.contentVersion)
        if self.nodes is not None:
            nodeslist = []
            for i in range(len(self.nodes)):
                nodeslist.append(self.nodes[i].Pack(builder))
            RouteGraphBufferStartNodesVector(builder, len(self.nodes))
            for i in reversed(range(len(self.nodes))):
                builder.PrependUOffsetTRelative(nodeslist[i])
            nodes = builder.EndVector()
        if self.edges is not None:
            edgeslist = []
            for i in range(len(self.edges)):
                edgeslist.append(self.edges[i].Pack(builder))
            RouteGraphBufferStartEdgesVector(builder, len(self.edges))
            for i in reversed(range(len(self.edges))):
                builder.PrependUOffsetTRelative(edgeslist[i])
            edges = builder.EndVector()
        if self.chunks is not None:
            chunkslist = []
            for i in range(len(self.chunks)):
                chunkslist.append(self.chunks[i].Pack(builder))
            RouteGraphBufferStartChunksVector(builder, len(self.chunks))
            for i in reversed(range(len(self.chunks))):
                builder.PrependUOffsetTRelative(chunkslist[i])
            chunks = builder.EndVector()
        if self.provenance is not None:
            provenance = self.provenance.Pack(builder)
        if self.spatialReference is not None:
            spatialReference = self.spatialReference.Pack(builder)
        RouteGraphBufferStart(builder)
        RouteGraphBufferAddSchemaVersion(builder, self.schemaVersion)
        if self.contentVersion is not None:
            RouteGraphBufferAddContentVersion(builder, contentVersion)
        if self.nodes is not None:
            RouteGraphBufferAddNodes(builder, nodes)
        if self.edges is not None:
            RouteGraphBufferAddEdges(builder, edges)
        if self.chunks is not None:
            RouteGraphBufferAddChunks(builder, chunks)
        if self.provenance is not None:
            RouteGraphBufferAddProvenance(builder, provenance)
        if self.spatialReference is not None:
            RouteGraphBufferAddSpatialReference(builder, spatialReference)
        routeGraphBuffer = RouteGraphBufferEnd(builder)
        return routeGraphBuffer
