# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Content

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RouteIdentityData(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RouteIdentityData()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRouteIdentityData(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def RouteIdentityDataBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x43\x42\x52\x47", size_prefixed=size_prefixed)

    # RouteIdentityData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RouteIdentityData
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RouteIdentityData
    def System(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RouteIdentityData
    def Number(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RouteIdentityData
    def Shield(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RouteIdentityData
    def SignedDirection(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RouteIdentityData
    def LocalName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RouteIdentityData
    def Provenance(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from Cannonball.Content.SemanticProvenanceData import SemanticProvenanceData
            obj = SemanticProvenanceData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def RouteIdentityDataStart(builder):
    builder.StartObject(7)

def Start(builder):
    RouteIdentityDataStart(builder)

def RouteIdentityDataAddId(builder, id):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)

def AddId(builder, id):
    RouteIdentityDataAddId(builder, id)

def RouteIdentityDataAddSystem(builder, system):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(system), 0)

def AddSystem(builder, system):
    RouteIdentityDataAddSystem(builder, system)

def RouteIdentityDataAddNumber(builder, number):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(number), 0)

def AddNumber(builder, number):
    RouteIdentityDataAddNumber(builder, number)

def RouteIdentityDataAddShield(builder, shield):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(shield), 0)

def AddShield(builder, shield):
    RouteIdentityDataAddShield(builder, shield)

def RouteIdentityDataAddSignedDirection(builder, signedDirection):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(signedDirection), 0)

def AddSignedDirection(builder, signedDirection):
    RouteIdentityDataAddSignedDirection(builder, signedDirection)

def RouteIdentityDataAddLocalName(builder, localName):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(localName), 0)

def AddLocalName(builder, localName):
    RouteIdentityDataAddLocalName(builder, localName)

def RouteIdentityDataAddProvenance(builder, provenance):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(provenance), 0)

def AddProvenance(builder, provenance):
    RouteIdentityDataAddProvenance(builder, provenance)

def RouteIdentityDataEnd(builder):
    return builder.EndObject()

def End(builder):
    return RouteIdentityDataEnd(builder)

import Cannonball.Content.SemanticProvenanceData
try:
    from typing import Optional
except:
    pass

class RouteIdentityDataT(object):

    # RouteIdentityDataT
    def __init__(
        self,
        id = None,
        system = None,
        number = None,
        shield = None,
        signedDirection = None,
        localName = None,
        provenance = None,
    ):
        self.id = id  # type: Optional[str]
        self.system = system  # type: Optional[str]
        self.number = number  # type: Optional[str]
        self.shield = shield  # type: Optional[str]
        self.signedDirection = signedDirection  # type: Optional[str]
        self.localName = localName  # type: Optional[str]
        self.provenance = provenance  # type: Optional[Cannonball.Content.SemanticProvenanceData.SemanticProvenanceDataT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        routeIdentityData = RouteIdentityData()
        routeIdentityData.Init(buf, pos)
        return cls.InitFromObj(routeIdentityData)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, routeIdentityData):
        x = RouteIdentityDataT()
        x._UnPack(routeIdentityData)
        return x

    # RouteIdentityDataT
    def _UnPack(self, routeIdentityData):
        if routeIdentityData is None:
            return
        self.id = routeIdentityData.Id()
        self.system = routeIdentityData.System()
        self.number = routeIdentityData.Number()
        self.shield = routeIdentityData.Shield()
        self.signedDirection = routeIdentityData.SignedDirection()
        self.localName = routeIdentityData.LocalName()
        if routeIdentityData.Provenance() is not None:
            self.provenance = Cannonball.Content.SemanticProvenanceData.SemanticProvenanceDataT.InitFromObj(routeIdentityData.Provenance())

    # RouteIdentityDataT
    def Pack(self, builder):
        if self.id is not None:
            id = builder.CreateString(self.id)
        if self.system is not None:
            system = builder.CreateString(self.system)
        if self.number is not None:
            number = builder.CreateString(self.number)
        if self.shield is not None:
            shield = builder.CreateString(self.shield)
        if self.signedDirection is not None:
            signedDirection = builder.CreateString(self.signedDirection)
        if self.localName is not None:
            localName = builder.CreateString(self.localName)
        if self.provenance is not None:
            provenance = self.provenance.Pack(builder)
        RouteIdentityDataStart(builder)
        if self.id is not None:
            RouteIdentityDataAddId(builder, id)
        if self.system is not None:
            RouteIdentityDataAddSystem(builder, system)
        if self.number is not None:
            RouteIdentityDataAddNumber(builder, number)
        if self.shield is not None:
            RouteIdentityDataAddShield(builder, shield)
        if self.signedDirection is not None:
            RouteIdentityDataAddSignedDirection(builder, signedDirection)
        if self.localName is not None:
            RouteIdentityDataAddLocalName(builder, localName)
        if self.provenance is not None:
            RouteIdentityDataAddProvenance(builder, provenance)
        routeIdentityData = RouteIdentityDataEnd(builder)
        return routeIdentityData
