# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Content

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RouteNodeData(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RouteNodeData()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRouteNodeData(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def RouteNodeDataBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x43\x42\x52\x47", size_prefixed=size_prefixed)

    # RouteNodeData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RouteNodeData
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RouteNodeData
    def Source(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            from Cannonball.Content.SourceCoordinate import SourceCoordinate
            obj = SourceCoordinate()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RouteNodeData
    def Kind(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RouteNodeData
    def OutgoingEdgeIds(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # RouteNodeData
    def OutgoingEdgeIdsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RouteNodeData
    def OutgoingEdgeIdsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

def RouteNodeDataStart(builder):
    builder.StartObject(4)

def Start(builder):
    RouteNodeDataStart(builder)

def RouteNodeDataAddId(builder, id):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)

def AddId(builder, id):
    RouteNodeDataAddId(builder, id)

def RouteNodeDataAddSource(builder, source):
    builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(source), 0)

def AddSource(builder, source):
    RouteNodeDataAddSource(builder, source)

def RouteNodeDataAddKind(builder, kind):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(kind), 0)

def AddKind(builder, kind):
    RouteNodeDataAddKind(builder, kind)

def RouteNodeDataAddOutgoingEdgeIds(builder, outgoingEdgeIds):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(outgoingEdgeIds), 0)

def AddOutgoingEdgeIds(builder, outgoingEdgeIds):
    RouteNodeDataAddOutgoingEdgeIds(builder, outgoingEdgeIds)

def RouteNodeDataStartOutgoingEdgeIdsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartOutgoingEdgeIdsVector(builder, numElems):
    return RouteNodeDataStartOutgoingEdgeIdsVector(builder, numElems)

def RouteNodeDataEnd(builder):
    return builder.EndObject()

def End(builder):
    return RouteNodeDataEnd(builder)

import Cannonball.Content.SourceCoordinate
try:
    from typing import List, Optional
except:
    pass

class RouteNodeDataT(object):

    # RouteNodeDataT
    def __init__(
        self,
        id = None,
        source = None,
        kind = None,
        outgoingEdgeIds = None,
    ):
        self.id = id  # type: Optional[str]
        self.source = source  # type: Optional[Cannonball.Content.SourceCoordinate.SourceCoordinateT]
        self.kind = kind  # type: Optional[str]
        self.outgoingEdgeIds = outgoingEdgeIds  # type: Optional[List[Optional[str]]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        routeNodeData = RouteNodeData()
        routeNodeData.Init(buf, pos)
        return cls.InitFromObj(routeNodeData)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, routeNodeData):
        x = RouteNodeDataT()
        x._UnPack(routeNodeData)
        return x

    # RouteNodeDataT
    def _UnPack(self, routeNodeData):
        if routeNodeData is None:
            return
        self.id = routeNodeData.Id()
        if routeNodeData.Source() is not None:
            self.source = Cannonball.Content.SourceCoordinate.SourceCoordinateT.InitFromObj(routeNodeData.Source())
        self.kind = routeNodeData.Kind()
        if not routeNodeData.OutgoingEdgeIdsIsNone():
            self.outgoingEdgeIds = []
            for i in range(routeNodeData.OutgoingEdgeIdsLength()):
                self.outgoingEdgeIds.append(routeNodeData.OutgoingEdgeIds(i))

    # RouteNodeDataT
    def Pack(self, builder):
        if self.id is not None:
            id = builder.CreateString(self.id)
        if self.kind is not None:
            kind = builder.CreateString(self.kind)
        if self.outgoingEdgeIds is not None:
            outgoingEdgeIdslist = []
            for i in range(len(self.outgoingEdgeIds)):
                outgoingEdgeIdslist.append(builder.CreateString(self.outgoingEdgeIds[i]))
            RouteNodeDataStartOutgoingEdgeIdsVector(builder, len(self.outgoingEdgeIds))
            for i in reversed(range(len(self.outgoingEdgeIds))):
                builder.PrependUOffsetTRelative(outgoingEdgeIdslist[i])
            outgoingEdgeIds = builder.EndVector()
        RouteNodeDataStart(builder)
        if self.id is not None:
            RouteNodeDataAddId(builder, id)
        if self.source is not None:
            source = self.source.Pack(builder)
            RouteNodeDataAddSource(builder, source)
        if self.kind is not None:
            RouteNodeDataAddKind(builder, kind)
        if self.outgoingEdgeIds is not None:
            RouteNodeDataAddOutgoingEdgeIds(builder, outgoingEdgeIds)
        routeNodeData = RouteNodeDataEnd(builder)
        return routeNodeData
