# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Content

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RouteEdgeData(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RouteEdgeData()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRouteEdgeData(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def RouteEdgeDataBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x43\x42\x52\x47", size_prefixed=size_prefixed)

    # RouteEdgeData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RouteEdgeData
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RouteEdgeData
    def FromNodeId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RouteEdgeData
    def ToNodeId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RouteEdgeData
    def LengthMeters(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # RouteEdgeData
    def LaneCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # RouteEdgeData
    def SpeedLimitMps(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # RouteEdgeData
    def RegionId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RouteEdgeData
    def GenerationProfile(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RouteEdgeData
    def ChunkIds(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # RouteEdgeData
    def ChunkIdsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RouteEdgeData
    def ChunkIdsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        return o == 0

    # RouteEdgeData
    def Samples(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 24
            from Cannonball.Content.RouteSample import RouteSample
            obj = RouteSample()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RouteEdgeData
    def SamplesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RouteEdgeData
    def SamplesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        return o == 0

    # RouteEdgeData
    def LaneSectionIds(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # RouteEdgeData
    def LaneSectionIdsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RouteEdgeData
    def LaneSectionIdsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        return o == 0

    # RouteEdgeData
    def RouteIdentityIds(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # RouteEdgeData
    def RouteIdentityIdsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RouteEdgeData
    def RouteIdentityIdsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        return o == 0

    # RouteEdgeData
    def RoadwayKind(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RouteEdgeData
    def CarriagewayGroupId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RouteEdgeData
    def OpposingEdgeId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def RouteEdgeDataStart(builder):
    builder.StartObject(15)

def Start(builder):
    RouteEdgeDataStart(builder)

def RouteEdgeDataAddId(builder, id):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)

def AddId(builder, id):
    RouteEdgeDataAddId(builder, id)

def RouteEdgeDataAddFromNodeId(builder, fromNodeId):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(fromNodeId), 0)

def AddFromNodeId(builder, fromNodeId):
    RouteEdgeDataAddFromNodeId(builder, fromNodeId)

def RouteEdgeDataAddToNodeId(builder, toNodeId):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(toNodeId), 0)

def AddToNodeId(builder, toNodeId):
    RouteEdgeDataAddToNodeId(builder, toNodeId)

def RouteEdgeDataAddLengthMeters(builder, lengthMeters):
    builder.PrependFloat64Slot(3, lengthMeters, 0.0)

def AddLengthMeters(builder, lengthMeters):
    RouteEdgeDataAddLengthMeters(builder, lengthMeters)

def RouteEdgeDataAddLaneCount(builder, laneCount):
    builder.PrependUint8Slot(4, laneCount, 0)

def AddLaneCount(builder, laneCount):
    RouteEdgeDataAddLaneCount(builder, laneCount)

def RouteEdgeDataAddSpeedLimitMps(builder, speedLimitMps):
    builder.PrependFloat32Slot(5, speedLimitMps, 0.0)

def AddSpeedLimitMps(builder, speedLimitMps):
    RouteEdgeDataAddSpeedLimitMps(builder, speedLimitMps)

def RouteEdgeDataAddRegionId(builder, regionId):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(regionId), 0)

def AddRegionId(builder, regionId):
    RouteEdgeDataAddRegionId(builder, regionId)

def RouteEdgeDataAddGenerationProfile(builder, generationProfile):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(generationProfile), 0)

def AddGenerationProfile(builder, generationProfile):
    RouteEdgeDataAddGenerationProfile(builder, generationProfile)

def RouteEdgeDataAddChunkIds(builder, chunkIds):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(chunkIds), 0)

def AddChunkIds(builder, chunkIds):
    RouteEdgeDataAddChunkIds(builder, chunkIds)

def RouteEdgeDataStartChunkIdsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartChunkIdsVector(builder, numElems):
    return RouteEdgeDataStartChunkIdsVector(builder, numElems)

def RouteEdgeDataAddSamples(builder, samples):
    builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(samples), 0)

def AddSamples(builder, samples):
    RouteEdgeDataAddSamples(builder, samples)

def RouteEdgeDataStartSamplesVector(builder, numElems):
    return builder.StartVector(24, numElems, 8)

def StartSamplesVector(builder, numElems):
    return RouteEdgeDataStartSamplesVector(builder, numElems)

def RouteEdgeDataAddLaneSectionIds(builder, laneSectionIds):
    builder.PrependUOffsetTRelativeSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(laneSectionIds), 0)

def AddLaneSectionIds(builder, laneSectionIds):
    RouteEdgeDataAddLaneSectionIds(builder, laneSectionIds)

def RouteEdgeDataStartLaneSectionIdsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartLaneSectionIdsVector(builder, numElems):
    return RouteEdgeDataStartLaneSectionIdsVector(builder, numElems)

def RouteEdgeDataAddRouteIdentityIds(builder, routeIdentityIds):
    builder.PrependUOffsetTRelativeSlot(11, flatbuffers.number_types.UOffsetTFlags.py_type(routeIdentityIds), 0)

def AddRouteIdentityIds(builder, routeIdentityIds):
    RouteEdgeDataAddRouteIdentityIds(builder, routeIdentityIds)

def RouteEdgeDataStartRouteIdentityIdsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartRouteIdentityIdsVector(builder, numElems):
    return RouteEdgeDataStartRouteIdentityIdsVector(builder, numElems)

def RouteEdgeDataAddRoadwayKind(builder, roadwayKind):
    builder.PrependUOffsetTRelativeSlot(12, flatbuffers.number_types.UOffsetTFlags.py_type(roadwayKind), 0)

def AddRoadwayKind(builder, roadwayKind):
    RouteEdgeDataAddRoadwayKind(builder, roadwayKind)

def RouteEdgeDataAddCarriagewayGroupId(builder, carriagewayGroupId):
    builder.PrependUOffsetTRelativeSlot(13, flatbuffers.number_types.UOffsetTFlags.py_type(carriagewayGroupId), 0)

def AddCarriagewayGroupId(builder, carriagewayGroupId):
    RouteEdgeDataAddCarriagewayGroupId(builder, carriagewayGroupId)

def RouteEdgeDataAddOpposingEdgeId(builder, opposingEdgeId):
    builder.PrependUOffsetTRelativeSlot(14, flatbuffers.number_types.UOffsetTFlags.py_type(opposingEdgeId), 0)

def AddOpposingEdgeId(builder, opposingEdgeId):
    RouteEdgeDataAddOpposingEdgeId(builder, opposingEdgeId)

def RouteEdgeDataEnd(builder):
    return builder.EndObject()

def End(builder):
    return RouteEdgeDataEnd(builder)

import Cannonball.Content.RouteSample
try:
    from typing import List
except:
    pass

class RouteEdgeDataT(object):

    # RouteEdgeDataT
    def __init__(
        self,
        id = None,
        fromNodeId = None,
        toNodeId = None,
        lengthMeters = 0.0,
        laneCount = 0,
        speedLimitMps = 0.0,
        regionId = None,
        generationProfile = None,
        chunkIds = None,
        samples = None,
        laneSectionIds = None,
        routeIdentityIds = None,
        roadwayKind = None,
        carriagewayGroupId = None,
        opposingEdgeId = None,
    ):
        self.id = id  # type: Optional[str]
        self.fromNodeId = fromNodeId  # type: Optional[str]
        self.toNodeId = toNodeId  # type: Optional[str]
        self.lengthMeters = lengthMeters  # type: float
        self.laneCount = laneCount  # type: int
        self.speedLimitMps = speedLimitMps  # type: float
        self.regionId = regionId  # type: Optional[str]
        self.generationProfile = generationProfile  # type: Optional[str]
        self.chunkIds = chunkIds  # type: Optional[List[Optional[str]]]
        self.samples = samples  # type: Optional[List[Cannonball.Content.RouteSample.RouteSampleT]]
        self.laneSectionIds = laneSectionIds  # type: Optional[List[Optional[str]]]
        self.routeIdentityIds = routeIdentityIds  # type: Optional[List[Optional[str]]]
        self.roadwayKind = roadwayKind  # type: Optional[str]
        self.carriagewayGroupId = carriagewayGroupId  # type: Optional[str]
        self.opposingEdgeId = opposingEdgeId  # type: Optional[str]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        routeEdgeData = RouteEdgeData()
        routeEdgeData.Init(buf, pos)
        return cls.InitFromObj(routeEdgeData)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, routeEdgeData):
        x = RouteEdgeDataT()
        x._UnPack(routeEdgeData)
        return x

    # RouteEdgeDataT
    def _UnPack(self, routeEdgeData):
        if routeEdgeData is None:
            return
        self.id = routeEdgeData.Id()
        self.fromNodeId = routeEdgeData.FromNodeId()
        self.toNodeId = routeEdgeData.ToNodeId()
        self.lengthMeters = routeEdgeData.LengthMeters()
        self.laneCount = routeEdgeData.LaneCount()
        self.speedLimitMps = routeEdgeData.SpeedLimitMps()
        self.regionId = routeEdgeData.RegionId()
        self.generationProfile = routeEdgeData.GenerationProfile()
        if not routeEdgeData.ChunkIdsIsNone():
            self.chunkIds = []
            for i in range(routeEdgeData.ChunkIdsLength()):
                self.chunkIds.append(routeEdgeData.ChunkIds(i))
        if not routeEdgeData.SamplesIsNone():
            self.samples = []
            for i in range(routeEdgeData.SamplesLength()):
                if routeEdgeData.Samples(i) is None:
                    self.samples.append(None)
                else:
                    routeSample_ = Cannonball.Content.RouteSample.RouteSampleT.InitFromObj(routeEdgeData.Samples(i))
                    self.samples.append(routeSample_)
        if not routeEdgeData.LaneSectionIdsIsNone():
            self.laneSectionIds = []
            for i in range(routeEdgeData.LaneSectionIdsLength()):
                self.laneSectionIds.append(routeEdgeData.LaneSectionIds(i))
        if not routeEdgeData.RouteIdentityIdsIsNone():
            self.routeIdentityIds = []
            for i in range(routeEdgeData.RouteIdentityIdsLength()):
                self.routeIdentityIds.append(routeEdgeData.RouteIdentityIds(i))
        self.roadwayKind = routeEdgeData.RoadwayKind()
        self.carriagewayGroupId = routeEdgeData.CarriagewayGroupId()
        self.opposingEdgeId = routeEdgeData.OpposingEdgeId()

    # RouteEdgeDataT
    def Pack(self, builder):
        if self.id is not None:
            id = builder.CreateString(self.id)
        if self.fromNodeId is not None:
            fromNodeId = builder.CreateString(self.fromNodeId)
        if self.toNodeId is not None:
            toNodeId = builder.CreateString(self.toNodeId)
        if self.regionId is not None:
            regionId = builder.CreateString(self.regionId)
        if self.generationProfile is not None:
            generationProfile = builder.CreateString(self.generationProfile)
        if self.chunkIds is not None:
            chunkIdslist = []
            for i in range(len(self.chunkIds)):
                chunkIdslist.append(builder.CreateString(self.chunkIds[i]))
            RouteEdgeDataStartChunkIdsVector(builder, len(self.chunkIds))
            for i in reversed(range(len(self.chunkIds))):
                builder.PrependUOffsetTRelative(chunkIdslist[i])
            chunkIds = builder.EndVector()
        if self.samples is not None:
            RouteEdgeDataStartSamplesVector(builder, len(self.samples))
            for i in reversed(range(len(self.samples))):
                self.samples[i].Pack(builder)
            samples = builder.EndVector()
        if self.laneSectionIds is not None:
            laneSectionIdslist = []
            for i in range(len(self.laneSectionIds)):
                laneSectionIdslist.append(builder.CreateString(self.laneSectionIds[i]))
            RouteEdgeDataStartLaneSectionIdsVector(builder, len(self.laneSectionIds))
            for i in reversed(range(len(self.laneSectionIds))):
                builder.PrependUOffsetTRelative(laneSectionIdslist[i])
            laneSectionIds = builder.EndVector()
        if self.routeIdentityIds is not None:
            routeIdentityIdslist = []
            for i in range(len(self.routeIdentityIds)):
                routeIdentityIdslist.append(builder.CreateString(self.routeIdentityIds[i]))
            RouteEdgeDataStartRouteIdentityIdsVector(builder, len(self.routeIdentityIds))
            for i in reversed(range(len(self.routeIdentityIds))):
                builder.PrependUOffsetTRelative(routeIdentityIdslist[i])
            routeIdentityIds = builder.EndVector()
        if self.roadwayKind is not None:
            roadwayKind = builder.CreateString(self.roadwayKind)
        if self.carriagewayGroupId is not None:
            carriagewayGroupId = builder.CreateString(self.carriagewayGroupId)
        if self.opposingEdgeId is not None:
            opposingEdgeId = builder.CreateString(self.opposingEdgeId)
        RouteEdgeDataStart(builder)
        if self.id is not None:
            RouteEdgeDataAddId(builder, id)
        if self.fromNodeId is not None:
            RouteEdgeDataAddFromNodeId(builder, fromNodeId)
        if self.toNodeId is not None:
            RouteEdgeDataAddToNodeId(builder, toNodeId)
        RouteEdgeDataAddLengthMeters(builder, self.lengthMeters)
        RouteEdgeDataAddLaneCount(builder, self.laneCount)
        RouteEdgeDataAddSpeedLimitMps(builder, self.speedLimitMps)
        if self.regionId is not None:
            RouteEdgeDataAddRegionId(builder, regionId)
        if self.generationProfile is not None:
            RouteEdgeDataAddGenerationProfile(builder, generationProfile)
        if self.chunkIds is not None:
            RouteEdgeDataAddChunkIds(builder, chunkIds)
        if self.samples is not None:
            RouteEdgeDataAddSamples(builder, samples)
        if self.laneSectionIds is not None:
            RouteEdgeDataAddLaneSectionIds(builder, laneSectionIds)
        if self.routeIdentityIds is not None:
            RouteEdgeDataAddRouteIdentityIds(builder, routeIdentityIds)
        if self.roadwayKind is not None:
            RouteEdgeDataAddRoadwayKind(builder, roadwayKind)
        if self.carriagewayGroupId is not None:
            RouteEdgeDataAddCarriagewayGroupId(builder, carriagewayGroupId)
        if self.opposingEdgeId is not None:
            RouteEdgeDataAddOpposingEdgeId(builder, opposingEdgeId)
        routeEdgeData = RouteEdgeDataEnd(builder)
        return routeEdgeData
