# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Content

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RouteLaneData(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RouteLaneData()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRouteLaneData(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def RouteLaneDataBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x43\x42\x52\x47", size_prefixed=size_prefixed)

    # RouteLaneData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RouteLaneData
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RouteLaneData
    def Index(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # RouteLaneData
    def WidthMeters(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # RouteLaneData
    def Role(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RouteLaneData
    def AllowedManeuvers(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # RouteLaneData
    def Provenance(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from Cannonball.Content.SemanticProvenanceData import SemanticProvenanceData
            obj = SemanticProvenanceData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def RouteLaneDataStart(builder):
    builder.StartObject(6)

def Start(builder):
    RouteLaneDataStart(builder)

def RouteLaneDataAddId(builder, id):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)

def AddId(builder, id):
    RouteLaneDataAddId(builder, id)

def RouteLaneDataAddIndex(builder, index):
    builder.PrependUint32Slot(1, index, 0)

def AddIndex(builder, index):
    RouteLaneDataAddIndex(builder, index)

def RouteLaneDataAddWidthMeters(builder, widthMeters):
    builder.PrependFloat32Slot(2, widthMeters, 0.0)

def AddWidthMeters(builder, widthMeters):
    RouteLaneDataAddWidthMeters(builder, widthMeters)

def RouteLaneDataAddRole(builder, role):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(role), 0)

def AddRole(builder, role):
    RouteLaneDataAddRole(builder, role)

def RouteLaneDataAddAllowedManeuvers(builder, allowedManeuvers):
    builder.PrependUint32Slot(4, allowedManeuvers, 0)

def AddAllowedManeuvers(builder, allowedManeuvers):
    RouteLaneDataAddAllowedManeuvers(builder, allowedManeuvers)

def RouteLaneDataAddProvenance(builder, provenance):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(provenance), 0)

def AddProvenance(builder, provenance):
    RouteLaneDataAddProvenance(builder, provenance)

def RouteLaneDataEnd(builder):
    return builder.EndObject()

def End(builder):
    return RouteLaneDataEnd(builder)

import Cannonball.Content.SemanticProvenanceData
try:
    from typing import Optional
except:
    pass

class RouteLaneDataT(object):

    # RouteLaneDataT
    def __init__(
        self,
        id = None,
        index = 0,
        widthMeters = 0.0,
        role = None,
        allowedManeuvers = 0,
        provenance = None,
    ):
        self.id = id  # type: Optional[str]
        self.index = index  # type: int
        self.widthMeters = widthMeters  # type: float
        self.role = role  # type: Optional[str]
        self.allowedManeuvers = allowedManeuvers  # type: int
        self.provenance = provenance  # type: Optional[Cannonball.Content.SemanticProvenanceData.SemanticProvenanceDataT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        routeLaneData = RouteLaneData()
        routeLaneData.Init(buf, pos)
        return cls.InitFromObj(routeLaneData)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, routeLaneData):
        x = RouteLaneDataT()
        x._UnPack(routeLaneData)
        return x

    # RouteLaneDataT
    def _UnPack(self, routeLaneData):
        if routeLaneData is None:
            return
        self.id = routeLaneData.Id()
        self.index = routeLaneData.Index()
        self.widthMeters = routeLaneData.WidthMeters()
        self.role = routeLaneData.Role()
        self.allowedManeuvers = routeLaneData.AllowedManeuvers()
        if routeLaneData.Provenance() is not None:
            self.provenance = Cannonball.Content.SemanticProvenanceData.SemanticProvenanceDataT.InitFromObj(routeLaneData.Provenance())

    # RouteLaneDataT
    def Pack(self, builder):
        if self.id is not None:
            id = builder.CreateString(self.id)
        if self.role is not None:
            role = builder.CreateString(self.role)
        if self.provenance is not None:
            provenance = self.provenance.Pack(builder)
        RouteLaneDataStart(builder)
        if self.id is not None:
            RouteLaneDataAddId(builder, id)
        RouteLaneDataAddIndex(builder, self.index)
        RouteLaneDataAddWidthMeters(builder, self.widthMeters)
        if self.role is not None:
            RouteLaneDataAddRole(builder, role)
        RouteLaneDataAddAllowedManeuvers(builder, self.allowedManeuvers)
        if self.provenance is not None:
            RouteLaneDataAddProvenance(builder, provenance)
        routeLaneData = RouteLaneDataEnd(builder)
        return routeLaneData
