# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Content

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RouteSample(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 24

    # RouteSample
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RouteSample
    def DistanceMeters(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # RouteSample
    def LateralMeters(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))
    # RouteSample
    def ElevationMeters(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(12))
    # RouteSample
    def Curvature(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(16))
    # RouteSample
    def Grade(self): return self._tab.Get(flatbuffers.number_types.Float32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(20))

def CreateRouteSample(builder, distanceMeters, lateralMeters, elevationMeters, curvature, grade):
    builder.Prep(8, 24)
    builder.PrependFloat32(grade)
    builder.PrependFloat32(curvature)
    builder.PrependFloat32(elevationMeters)
    builder.PrependFloat32(lateralMeters)
    builder.PrependFloat64(distanceMeters)
    return builder.Offset()


class RouteSampleT(object):

    # RouteSampleT
    def __init__(
        self,
        distanceMeters = 0.0,
        lateralMeters = 0.0,
        elevationMeters = 0.0,
        curvature = 0.0,
        grade = 0.0,
    ):
        self.distanceMeters = distanceMeters  # type: float
        self.lateralMeters = lateralMeters  # type: float
        self.elevationMeters = elevationMeters  # type: float
        self.curvature = curvature  # type: float
        self.grade = grade  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        routeSample = RouteSample()
        routeSample.Init(buf, pos)
        return cls.InitFromObj(routeSample)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, routeSample):
        x = RouteSampleT()
        x._UnPack(routeSample)
        return x

    # RouteSampleT
    def _UnPack(self, routeSample):
        if routeSample is None:
            return
        self.distanceMeters = routeSample.DistanceMeters()
        self.lateralMeters = routeSample.LateralMeters()
        self.elevationMeters = routeSample.ElevationMeters()
        self.curvature = routeSample.Curvature()
        self.grade = routeSample.Grade()

    # RouteSampleT
    def Pack(self, builder):
        return CreateRouteSample(builder, self.distanceMeters, self.lateralMeters, self.elevationMeters, self.curvature, self.grade)
