# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Content

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RouteChunkBuffer(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RouteChunkBuffer()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRouteChunkBuffer(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def RouteChunkBufferBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x43\x42\x43\x4B", size_prefixed=size_prefixed)

    # RouteChunkBuffer
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RouteChunkBuffer
    def SchemaVersion(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # RouteChunkBuffer
    def ContentVersion(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RouteChunkBuffer
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RouteChunkBuffer
    def EdgeId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RouteChunkBuffer
    def StartMeters(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # RouteChunkBuffer
    def EndMeters(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # RouteChunkBuffer
    def Samples(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 56
            from Cannonball.Content.ChunkRouteSample import ChunkRouteSample
            obj = ChunkRouteSample()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RouteChunkBuffer
    def SamplesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RouteChunkBuffer
    def SamplesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

def RouteChunkBufferStart(builder):
    builder.StartObject(7)

def Start(builder):
    RouteChunkBufferStart(builder)

def RouteChunkBufferAddSchemaVersion(builder, schemaVersion):
    builder.PrependUint32Slot(0, schemaVersion, 0)

def AddSchemaVersion(builder, schemaVersion):
    RouteChunkBufferAddSchemaVersion(builder, schemaVersion)

def RouteChunkBufferAddContentVersion(builder, contentVersion):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(contentVersion), 0)

def AddContentVersion(builder, contentVersion):
    RouteChunkBufferAddContentVersion(builder, contentVersion)

def RouteChunkBufferAddId(builder, id):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)

def AddId(builder, id):
    RouteChunkBufferAddId(builder, id)

def RouteChunkBufferAddEdgeId(builder, edgeId):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(edgeId), 0)

def AddEdgeId(builder, edgeId):
    RouteChunkBufferAddEdgeId(builder, edgeId)

def RouteChunkBufferAddStartMeters(builder, startMeters):
    builder.PrependFloat64Slot(4, startMeters, 0.0)

def AddStartMeters(builder, startMeters):
    RouteChunkBufferAddStartMeters(builder, startMeters)

def RouteChunkBufferAddEndMeters(builder, endMeters):
    builder.PrependFloat64Slot(5, endMeters, 0.0)

def AddEndMeters(builder, endMeters):
    RouteChunkBufferAddEndMeters(builder, endMeters)

def RouteChunkBufferAddSamples(builder, samples):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(samples), 0)

def AddSamples(builder, samples):
    RouteChunkBufferAddSamples(builder, samples)

def RouteChunkBufferStartSamplesVector(builder, numElems):
    return builder.StartVector(56, numElems, 8)

def StartSamplesVector(builder, numElems):
    return RouteChunkBufferStartSamplesVector(builder, numElems)

def RouteChunkBufferEnd(builder):
    return builder.EndObject()

def End(builder):
    return RouteChunkBufferEnd(builder)

import Cannonball.Content.ChunkRouteSample
try:
    from typing import List
except:
    pass

class RouteChunkBufferT(object):

    # RouteChunkBufferT
    def __init__(
        self,
        schemaVersion = 0,
        contentVersion = None,
        id = None,
        edgeId = None,
        startMeters = 0.0,
        endMeters = 0.0,
        samples = None,
    ):
        self.schemaVersion = schemaVersion  # type: int
        self.contentVersion = contentVersion  # type: Optional[str]
        self.id = id  # type: Optional[str]
        self.edgeId = edgeId  # type: Optional[str]
        self.startMeters = startMeters  # type: float
        self.endMeters = endMeters  # type: float
        self.samples = samples  # type: Optional[List[Cannonball.Content.ChunkRouteSample.ChunkRouteSampleT]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        routeChunkBuffer = RouteChunkBuffer()
        routeChunkBuffer.Init(buf, pos)
        return cls.InitFromObj(routeChunkBuffer)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, routeChunkBuffer):
        x = RouteChunkBufferT()
        x._UnPack(routeChunkBuffer)
        return x

    # RouteChunkBufferT
    def _UnPack(self, routeChunkBuffer):
        if routeChunkBuffer is None:
            return
        self.schemaVersion = routeChunkBuffer.SchemaVersion()
        self.contentVersion = routeChunkBuffer.ContentVersion()
        self.id = routeChunkBuffer.Id()
        self.edgeId = routeChunkBuffer.EdgeId()
        self.startMeters = routeChunkBuffer.StartMeters()
        self.endMeters = routeChunkBuffer.EndMeters()
        if not routeChunkBuffer.SamplesIsNone():
            self.samples = []
            for i in range(routeChunkBuffer.SamplesLength()):
                if routeChunkBuffer.Samples(i) is None:
                    self.samples.append(None)
                else:
                    chunkRouteSample_ = Cannonball.Content.ChunkRouteSample.ChunkRouteSampleT.InitFromObj(routeChunkBuffer.Samples(i))
                    self.samples.append(chunkRouteSample_)

    # RouteChunkBufferT
    def Pack(self, builder):
        if self.contentVersion is not None:
            contentVersion = builder.CreateString(self.contentVersion)
        if self.id is not None:
            id = builder.CreateString(self.id)
        if self.edgeId is not None:
            edgeId = builder.CreateString(self.edgeId)
        if self.samples is not None:
            RouteChunkBufferStartSamplesVector(builder, len(self.samples))
            for i in reversed(range(len(self.samples))):
                self.samples[i].Pack(builder)
            samples = builder.EndVector()
        RouteChunkBufferStart(builder)
        RouteChunkBufferAddSchemaVersion(builder, self.schemaVersion)
        if self.contentVersion is not None:
            RouteChunkBufferAddContentVersion(builder, contentVersion)
        if self.id is not None:
            RouteChunkBufferAddId(builder, id)
        if self.edgeId is not None:
            RouteChunkBufferAddEdgeId(builder, edgeId)
        RouteChunkBufferAddStartMeters(builder, self.startMeters)
        RouteChunkBufferAddEndMeters(builder, self.endMeters)
        if self.samples is not None:
            RouteChunkBufferAddSamples(builder, samples)
        routeChunkBuffer = RouteChunkBufferEnd(builder)
        return routeChunkBuffer
