# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Content

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RouteGraphBuffer(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RouteGraphBuffer()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRouteGraphBuffer(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def RouteGraphBufferBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x43\x42\x52\x47", size_prefixed=size_prefixed)

    # RouteGraphBuffer
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RouteGraphBuffer
    def SchemaVersion(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # RouteGraphBuffer
    def ContentVersion(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RouteGraphBuffer
    def Nodes(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Cannonball.Content.RouteNodeData import RouteNodeData
            obj = RouteNodeData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RouteGraphBuffer
    def NodesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RouteGraphBuffer
    def NodesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # RouteGraphBuffer
    def Edges(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Cannonball.Content.RouteEdgeData import RouteEdgeData
            obj = RouteEdgeData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RouteGraphBuffer
    def EdgesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RouteGraphBuffer
    def EdgesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # RouteGraphBuffer
    def Chunks(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Cannonball.Content.ChunkManifestData import ChunkManifestData
            obj = ChunkManifestData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RouteGraphBuffer
    def ChunksLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RouteGraphBuffer
    def ChunksIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # RouteGraphBuffer
    def Provenance(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from Cannonball.Content.SourceProvenanceData import SourceProvenanceData
            obj = SourceProvenanceData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RouteGraphBuffer
    def SpatialReference(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from Cannonball.Content.SpatialReferenceData import SpatialReferenceData
            obj = SpatialReferenceData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RouteGraphBuffer
    def LaneSections(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Cannonball.Content.LaneSectionData import LaneSectionData
            obj = LaneSectionData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RouteGraphBuffer
    def LaneSectionsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RouteGraphBuffer
    def LaneSectionsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        return o == 0

    # RouteGraphBuffer
    def JunctionConnectors(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Cannonball.Content.JunctionConnectorData import JunctionConnectorData
            obj = JunctionConnectorData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RouteGraphBuffer
    def JunctionConnectorsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RouteGraphBuffer
    def JunctionConnectorsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        return o == 0

    # RouteGraphBuffer
    def RouteIdentities(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Cannonball.Content.RouteIdentityData import RouteIdentityData
            obj = RouteIdentityData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RouteGraphBuffer
    def RouteIdentitiesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RouteGraphBuffer
    def RouteIdentitiesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        return o == 0

    # RouteGraphBuffer
    def Exits(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Cannonball.Content.ExitData import ExitData
            obj = ExitData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RouteGraphBuffer
    def ExitsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RouteGraphBuffer
    def ExitsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        return o == 0

    # RouteGraphBuffer
    def MilepointAnchors(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Cannonball.Content.MilepointAnchorData import MilepointAnchorData
            obj = MilepointAnchorData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RouteGraphBuffer
    def MilepointAnchorsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RouteGraphBuffer
    def MilepointAnchorsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        return o == 0

    # RouteGraphBuffer
    def RoadsideMarkers(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Cannonball.Content.RoadsideMarkerData import RoadsideMarkerData
            obj = RoadsideMarkerData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RouteGraphBuffer
    def RoadsideMarkersLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RouteGraphBuffer
    def RoadsideMarkersIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        return o == 0

    # RouteGraphBuffer
    def SimplifiedMapGeometry(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Cannonball.Content.SimplifiedMapGeometryData import SimplifiedMapGeometryData
            obj = SimplifiedMapGeometryData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RouteGraphBuffer
    def SimplifiedMapGeometryLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RouteGraphBuffer
    def SimplifiedMapGeometryIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        return o == 0

def RouteGraphBufferStart(builder):
    builder.StartObject(14)

def Start(builder):
    RouteGraphBufferStart(builder)

def RouteGraphBufferAddSchemaVersion(builder, schemaVersion):
    builder.PrependUint32Slot(0, schemaVersion, 0)

def AddSchemaVersion(builder, schemaVersion):
    RouteGraphBufferAddSchemaVersion(builder, schemaVersion)

def RouteGraphBufferAddContentVersion(builder, contentVersion):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(contentVersion), 0)

def AddContentVersion(builder, contentVersion):
    RouteGraphBufferAddContentVersion(builder, contentVersion)

def RouteGraphBufferAddNodes(builder, nodes):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(nodes), 0)

def AddNodes(builder, nodes):
    RouteGraphBufferAddNodes(builder, nodes)

def RouteGraphBufferStartNodesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartNodesVector(builder, numElems):
    return RouteGraphBufferStartNodesVector(builder, numElems)

def RouteGraphBufferAddEdges(builder, edges):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(edges), 0)

def AddEdges(builder, edges):
    RouteGraphBufferAddEdges(builder, edges)

def RouteGraphBufferStartEdgesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartEdgesVector(builder, numElems):
    return RouteGraphBufferStartEdgesVector(builder, numElems)

def RouteGraphBufferAddChunks(builder, chunks):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(chunks), 0)

def AddChunks(builder, chunks):
    RouteGraphBufferAddChunks(builder, chunks)

def RouteGraphBufferStartChunksVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartChunksVector(builder, numElems):
    return RouteGraphBufferStartChunksVector(builder, numElems)

def RouteGraphBufferAddProvenance(builder, provenance):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(provenance), 0)

def AddProvenance(builder, provenance):
    RouteGraphBufferAddProvenance(builder, provenance)

def RouteGraphBufferAddSpatialReference(builder, spatialReference):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(spatialReference), 0)

def AddSpatialReference(builder, spatialReference):
    RouteGraphBufferAddSpatialReference(builder, spatialReference)

def RouteGraphBufferAddLaneSections(builder, laneSections):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(laneSections), 0)

def AddLaneSections(builder, laneSections):
    RouteGraphBufferAddLaneSections(builder, laneSections)

def RouteGraphBufferStartLaneSectionsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartLaneSectionsVector(builder, numElems):
    return RouteGraphBufferStartLaneSectionsVector(builder, numElems)

def RouteGraphBufferAddJunctionConnectors(builder, junctionConnectors):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(junctionConnectors), 0)

def AddJunctionConnectors(builder, junctionConnectors):
    RouteGraphBufferAddJunctionConnectors(builder, junctionConnectors)

def RouteGraphBufferStartJunctionConnectorsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartJunctionConnectorsVector(builder, numElems):
    return RouteGraphBufferStartJunctionConnectorsVector(builder, numElems)

def RouteGraphBufferAddRouteIdentities(builder, routeIdentities):
    builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(routeIdentities), 0)

def AddRouteIdentities(builder, routeIdentities):
    RouteGraphBufferAddRouteIdentities(builder, routeIdentities)

def RouteGraphBufferStartRouteIdentitiesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartRouteIdentitiesVector(builder, numElems):
    return RouteGraphBufferStartRouteIdentitiesVector(builder, numElems)

def RouteGraphBufferAddExits(builder, exits):
    builder.PrependUOffsetTRelativeSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(exits), 0)

def AddExits(builder, exits):
    RouteGraphBufferAddExits(builder, exits)

def RouteGraphBufferStartExitsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartExitsVector(builder, numElems):
    return RouteGraphBufferStartExitsVector(builder, numElems)

def RouteGraphBufferAddMilepointAnchors(builder, milepointAnchors):
    builder.PrependUOffsetTRelativeSlot(11, flatbuffers.number_types.UOffsetTFlags.py_type(milepointAnchors), 0)

def AddMilepointAnchors(builder, milepointAnchors):
    RouteGraphBufferAddMilepointAnchors(builder, milepointAnchors)

def RouteGraphBufferStartMilepointAnchorsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartMilepointAnchorsVector(builder, numElems):
    return RouteGraphBufferStartMilepointAnchorsVector(builder, numElems)

def RouteGraphBufferAddRoadsideMarkers(builder, roadsideMarkers):
    builder.PrependUOffsetTRelativeSlot(12, flatbuffers.number_types.UOffsetTFlags.py_type(roadsideMarkers), 0)

def AddRoadsideMarkers(builder, roadsideMarkers):
    RouteGraphBufferAddRoadsideMarkers(builder, roadsideMarkers)

def RouteGraphBufferStartRoadsideMarkersVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartRoadsideMarkersVector(builder, numElems):
    return RouteGraphBufferStartRoadsideMarkersVector(builder, numElems)

def RouteGraphBufferAddSimplifiedMapGeometry(builder, simplifiedMapGeometry):
    builder.PrependUOffsetTRelativeSlot(13, flatbuffers.number_types.UOffsetTFlags.py_type(simplifiedMapGeometry), 0)

def AddSimplifiedMapGeometry(builder, simplifiedMapGeometry):
    RouteGraphBufferAddSimplifiedMapGeometry(builder, simplifiedMapGeometry)

def RouteGraphBufferStartSimplifiedMapGeometryVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartSimplifiedMapGeometryVector(builder, numElems):
    return RouteGraphBufferStartSimplifiedMapGeometryVector(builder, numElems)

def RouteGraphBufferEnd(builder):
    return builder.EndObject()

def End(builder):
    return RouteGraphBufferEnd(builder)

import Cannonball.Content.ChunkManifestData
import Cannonball.Content.ExitData
import Cannonball.Content.JunctionConnectorData
import Cannonball.Content.LaneSectionData
import Cannonball.Content.MilepointAnchorData
import Cannonball.Content.RoadsideMarkerData
import Cannonball.Content.RouteEdgeData
import Cannonball.Content.RouteIdentityData
import Cannonball.Content.RouteNodeData
import Cannonball.Content.SimplifiedMapGeometryData
import Cannonball.Content.SourceProvenanceData
import Cannonball.Content.SpatialReferenceData
try:
    from typing import List, Optional
except:
    pass

class RouteGraphBufferT(object):

    # RouteGraphBufferT
    def __init__(
        self,
        schemaVersion = 0,
        contentVersion = None,
        nodes = None,
        edges = None,
        chunks = None,
        provenance = None,
        spatialReference = None,
        laneSections = None,
        junctionConnectors = None,
        routeIdentities = None,
        exits = None,
        milepointAnchors = None,
        roadsideMarkers = None,
        simplifiedMapGeometry = None,
    ):
        self.schemaVersion = schemaVersion  # type: int
        self.contentVersion = contentVersion  # type: Optional[str]
        self.nodes = nodes  # type: Optional[List[Cannonball.Content.RouteNodeData.RouteNodeDataT]]
        self.edges = edges  # type: Optional[List[Cannonball.Content.RouteEdgeData.RouteEdgeDataT]]
        self.chunks = chunks  # type: Optional[List[Cannonball.Content.ChunkManifestData.ChunkManifestDataT]]
        self.provenance = provenance  # type: Optional[Cannonball.Content.SourceProvenanceData.SourceProvenanceDataT]
        self.spatialReference = spatialReference  # type: Optional[Cannonball.Content.SpatialReferenceData.SpatialReferenceDataT]
        self.laneSections = laneSections  # type: Optional[List[Cannonball.Content.LaneSectionData.LaneSectionDataT]]
        self.junctionConnectors = junctionConnectors  # type: Optional[List[Cannonball.Content.JunctionConnectorData.JunctionConnectorDataT]]
        self.routeIdentities = routeIdentities  # type: Optional[List[Cannonball.Content.RouteIdentityData.RouteIdentityDataT]]
        self.exits = exits  # type: Optional[List[Cannonball.Content.ExitData.ExitDataT]]
        self.milepointAnchors = milepointAnchors  # type: Optional[List[Cannonball.Content.MilepointAnchorData.MilepointAnchorDataT]]
        self.roadsideMarkers = roadsideMarkers  # type: Optional[List[Cannonball.Content.RoadsideMarkerData.RoadsideMarkerDataT]]
        self.simplifiedMapGeometry = simplifiedMapGeometry  # type: Optional[List[Cannonball.Content.SimplifiedMapGeometryData.SimplifiedMapGeometryDataT]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        routeGraphBuffer = RouteGraphBuffer()
        routeGraphBuffer.Init(buf, pos)
        return cls.InitFromObj(routeGraphBuffer)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, routeGraphBuffer):
        x = RouteGraphBufferT()
        x._UnPack(routeGraphBuffer)
        return x

    # RouteGraphBufferT
    def _UnPack(self, routeGraphBuffer):
        if routeGraphBuffer is None:
            return
        self.schemaVersion = routeGraphBuffer.SchemaVersion()
        self.contentVersion = routeGraphBuffer.ContentVersion()
        if not routeGraphBuffer.NodesIsNone():
            self.nodes = []
            for i in range(routeGraphBuffer.NodesLength()):
                if routeGraphBuffer.Nodes(i) is None:
                    self.nodes.append(None)
                else:
                    routeNodeData_ = Cannonball.Content.RouteNodeData.RouteNodeDataT.InitFromObj(routeGraphBuffer.Nodes(i))
                    self.nodes.append(routeNodeData_)
        if not routeGraphBuffer.EdgesIsNone():
            self.edges = []
            for i in range(routeGraphBuffer.EdgesLength()):
                if routeGraphBuffer.Edges(i) is None:
                    self.edges.append(None)
                else:
                    routeEdgeData_ = Cannonball.Content.RouteEdgeData.RouteEdgeDataT.InitFromObj(routeGraphBuffer.Edges(i))
                    self.edges.append(routeEdgeData_)
        if not routeGraphBuffer.ChunksIsNone():
            self.chunks = []
            for i in range(routeGraphBuffer.ChunksLength()):
                if routeGraphBuffer.Chunks(i) is None:
                    self.chunks.append(None)
                else:
                    chunkManifestData_ = Cannonball.Content.ChunkManifestData.ChunkManifestDataT.InitFromObj(routeGraphBuffer.Chunks(i))
                    self.chunks.append(chunkManifestData_)
        if routeGraphBuffer.Provenance() is not None:
            self.provenance = Cannonball.Content.SourceProvenanceData.SourceProvenanceDataT.InitFromObj(routeGraphBuffer.Provenance())
        if routeGraphBuffer.SpatialReference() is not None:
            self.spatialReference = Cannonball.Content.SpatialReferenceData.SpatialReferenceDataT.InitFromObj(routeGraphBuffer.SpatialReference())
        if not routeGraphBuffer.LaneSectionsIsNone():
            self.laneSections = []
            for i in range(routeGraphBuffer.LaneSectionsLength()):
                if routeGraphBuffer.LaneSections(i) is None:
                    self.laneSections.append(None)
                else:
                    laneSectionData_ = Cannonball.Content.LaneSectionData.LaneSectionDataT.InitFromObj(routeGraphBuffer.LaneSections(i))
                    self.laneSections.append(laneSectionData_)
        if not routeGraphBuffer.JunctionConnectorsIsNone():
            self.junctionConnectors = []
            for i in range(routeGraphBuffer.JunctionConnectorsLength()):
                if routeGraphBuffer.JunctionConnectors(i) is None:
                    self.junctionConnectors.append(None)
                else:
                    junctionConnectorData_ = Cannonball.Content.JunctionConnectorData.JunctionConnectorDataT.InitFromObj(routeGraphBuffer.JunctionConnectors(i))
                    self.junctionConnectors.append(junctionConnectorData_)
        if not routeGraphBuffer.RouteIdentitiesIsNone():
            self.routeIdentities = []
            for i in range(routeGraphBuffer.RouteIdentitiesLength()):
                if routeGraphBuffer.RouteIdentities(i) is None:
                    self.routeIdentities.append(None)
                else:
                    routeIdentityData_ = Cannonball.Content.RouteIdentityData.RouteIdentityDataT.InitFromObj(routeGraphBuffer.RouteIdentities(i))
                    self.routeIdentities.append(routeIdentityData_)
        if not routeGraphBuffer.ExitsIsNone():
            self.exits = []
            for i in range(routeGraphBuffer.ExitsLength()):
                if routeGraphBuffer.Exits(i) is None:
                    self.exits.append(None)
                else:
                    exitData_ = Cannonball.Content.ExitData.ExitDataT.InitFromObj(routeGraphBuffer.Exits(i))
                    self.exits.append(exitData_)
        if not routeGraphBuffer.MilepointAnchorsIsNone():
            self.milepointAnchors = []
            for i in range(routeGraphBuffer.MilepointAnchorsLength()):
                if routeGraphBuffer.MilepointAnchors(i) is None:
                    self.milepointAnchors.append(None)
                else:
                    milepointAnchorData_ = Cannonball.Content.MilepointAnchorData.MilepointAnchorDataT.InitFromObj(routeGraphBuffer.MilepointAnchors(i))
                    self.milepointAnchors.append(milepointAnchorData_)
        if not routeGraphBuffer.RoadsideMarkersIsNone():
            self.roadsideMarkers = []
            for i in range(routeGraphBuffer.RoadsideMarkersLength()):
                if routeGraphBuffer.RoadsideMarkers(i) is None:
                    self.roadsideMarkers.append(None)
                else:
                    roadsideMarkerData_ = Cannonball.Content.RoadsideMarkerData.RoadsideMarkerDataT.InitFromObj(routeGraphBuffer.RoadsideMarkers(i))
                    self.roadsideMarkers.append(roadsideMarkerData_)
        if not routeGraphBuffer.SimplifiedMapGeometryIsNone():
            self.simplifiedMapGeometry = []
            for i in range(routeGraphBuffer.SimplifiedMapGeometryLength()):
                if routeGraphBuffer.SimplifiedMapGeometry(i) is None:
                    self.simplifiedMapGeometry.append(None)
                else:
                    simplifiedMapGeometryData_ = Cannonball.Content.SimplifiedMapGeometryData.SimplifiedMapGeometryDataT.InitFromObj(routeGraphBuffer.SimplifiedMapGeometry(i))
                    self.simplifiedMapGeometry.append(simplifiedMapGeometryData_)

    # RouteGraphBufferT
    def Pack(self, builder):
        if self.contentVersion is not None:
            contentVersion = builder.CreateString(self.contentVersion)
        if self.nodes is not None:
            nodeslist = []
            for i in range(len(self.nodes)):
                nodeslist.append(self.nodes[i].Pack(builder))
            RouteGraphBufferStartNodesVector(builder, len(self.nodes))
            for i in reversed(range(len(self.nodes))):
                builder.PrependUOffsetTRelative(nodeslist[i])
            nodes = builder.EndVector()
        if self.edges is not None:
            edgeslist = []
            for i in range(len(self.edges)):
                edgeslist.append(self.edges[i].Pack(builder))
            RouteGraphBufferStartEdgesVector(builder, len(self.edges))
            for i in reversed(range(len(self.edges))):
                builder.PrependUOffsetTRelative(edgeslist[i])
            edges = builder.EndVector()
        if self.chunks is not None:
            chunkslist = []
            for i in range(len(self.chunks)):
                chunkslist.append(self.chunks[i].Pack(builder))
            RouteGraphBufferStartChunksVector(builder, len(self.chunks))
            for i in reversed(range(len(self.chunks))):
                builder.PrependUOffsetTRelative(chunkslist[i])
            chunks = builder.EndVector()
        if self.provenance is not None:
            provenance = self.provenance.Pack(builder)
        if self.spatialReference is not None:
            spatialReference = self.spatialReference.Pack(builder)
        if self.laneSections is not None:
            laneSectionslist = []
            for i in range(len(self.laneSections)):
                laneSectionslist.append(self.laneSections[i].Pack(builder))
            RouteGraphBufferStartLaneSectionsVector(builder, len(self.laneSections))
            for i in reversed(range(len(self.laneSections))):
                builder.PrependUOffsetTRelative(laneSectionslist[i])
            laneSections = builder.EndVector()
        if self.junctionConnectors is not None:
            junctionConnectorslist = []
            for i in range(len(self.junctionConnectors)):
                junctionConnectorslist.append(self.junctionConnectors[i].Pack(builder))
            RouteGraphBufferStartJunctionConnectorsVector(builder, len(self.junctionConnectors))
            for i in reversed(range(len(self.junctionConnectors))):
                builder.PrependUOffsetTRelative(junctionConnectorslist[i])
            junctionConnectors = builder.EndVector()
        if self.routeIdentities is not None:
            routeIdentitieslist = []
            for i in range(len(self.routeIdentities)):
                routeIdentitieslist.append(self.routeIdentities[i].Pack(builder))
            RouteGraphBufferStartRouteIdentitiesVector(builder, len(self.routeIdentities))
            for i in reversed(range(len(self.routeIdentities))):
                builder.PrependUOffsetTRelative(routeIdentitieslist[i])
            routeIdentities = builder.EndVector()
        if self.exits is not None:
            exitslist = []
            for i in range(len(self.exits)):
                exitslist.append(self.exits[i].Pack(builder))
            RouteGraphBufferStartExitsVector(builder, len(self.exits))
            for i in reversed(range(len(self.exits))):
                builder.PrependUOffsetTRelative(exitslist[i])
            exits = builder.EndVector()
        if self.milepointAnchors is not None:
            milepointAnchorslist = []
            for i in range(len(self.milepointAnchors)):
                milepointAnchorslist.append(self.milepointAnchors[i].Pack(builder))
            RouteGraphBufferStartMilepointAnchorsVector(builder, len(self.milepointAnchors))
            for i in reversed(range(len(self.milepointAnchors))):
                builder.PrependUOffsetTRelative(milepointAnchorslist[i])
            milepointAnchors = builder.EndVector()
        if self.roadsideMarkers is not None:
            roadsideMarkerslist = []
            for i in range(len(self.roadsideMarkers)):
                roadsideMarkerslist.append(self.roadsideMarkers[i].Pack(builder))
            RouteGraphBufferStartRoadsideMarkersVector(builder, len(self.roadsideMarkers))
            for i in reversed(range(len(self.roadsideMarkers))):
                builder.PrependUOffsetTRelative(roadsideMarkerslist[i])
            roadsideMarkers = builder.EndVector()
        if self.simplifiedMapGeometry is not None:
            simplifiedMapGeometrylist = []
            for i in range(len(self.simplifiedMapGeometry)):
                simplifiedMapGeometrylist.append(self.simplifiedMapGeometry[i].Pack(builder))
            RouteGraphBufferStartSimplifiedMapGeometryVector(builder, len(self.simplifiedMapGeometry))
            for i in reversed(range(len(self.simplifiedMapGeometry))):
                builder.PrependUOffsetTRelative(simplifiedMapGeometrylist[i])
            simplifiedMapGeometry = builder.EndVector()
        RouteGraphBufferStart(builder)
        RouteGraphBufferAddSchemaVersion(builder, self.schemaVersion)
        if self.contentVersion is not None:
            RouteGraphBufferAddContentVersion(builder, contentVersion)
        if self.nodes is not None:
            RouteGraphBufferAddNodes(builder, nodes)
        if self.edges is not None:
            RouteGraphBufferAddEdges(builder, edges)
        if self.chunks is not None:
            RouteGraphBufferAddChunks(builder, chunks)
        if self.provenance is not None:
            RouteGraphBufferAddProvenance(builder, provenance)
        if self.spatialReference is not None:
            RouteGraphBufferAddSpatialReference(builder, spatialReference)
        if self.laneSections is not None:
            RouteGraphBufferAddLaneSections(builder, laneSections)
        if self.junctionConnectors is not None:
            RouteGraphBufferAddJunctionConnectors(builder, junctionConnectors)
        if self.routeIdentities is not None:
            RouteGraphBufferAddRouteIdentities(builder, routeIdentities)
        if self.exits is not None:
            RouteGraphBufferAddExits(builder, exits)
        if self.milepointAnchors is not None:
            RouteGraphBufferAddMilepointAnchors(builder, milepointAnchors)
        if self.roadsideMarkers is not None:
            RouteGraphBufferAddRoadsideMarkers(builder, roadsideMarkers)
        if self.simplifiedMapGeometry is not None:
            RouteGraphBufferAddSimplifiedMapGeometry(builder, simplifiedMapGeometry)
        routeGraphBuffer = RouteGraphBufferEnd(builder)
        return routeGraphBuffer
