# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Content

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SemanticProvenanceData(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SemanticProvenanceData()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSemanticProvenanceData(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def SemanticProvenanceDataBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x43\x42\x52\x47", size_prefixed=size_prefixed)

    # SemanticProvenanceData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SemanticProvenanceData
    def Kind(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SemanticProvenanceData
    def SourceId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SemanticProvenanceData
    def SourceRecordId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SemanticProvenanceData
    def ArtifactSha256(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SemanticProvenanceData
    def Derivation(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SemanticProvenanceData
    def AuthoredOverrideId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def SemanticProvenanceDataStart(builder):
    builder.StartObject(6)

def Start(builder):
    SemanticProvenanceDataStart(builder)

def SemanticProvenanceDataAddKind(builder, kind):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(kind), 0)

def AddKind(builder, kind):
    SemanticProvenanceDataAddKind(builder, kind)

def SemanticProvenanceDataAddSourceId(builder, sourceId):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(sourceId), 0)

def AddSourceId(builder, sourceId):
    SemanticProvenanceDataAddSourceId(builder, sourceId)

def SemanticProvenanceDataAddSourceRecordId(builder, sourceRecordId):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(sourceRecordId), 0)

def AddSourceRecordId(builder, sourceRecordId):
    SemanticProvenanceDataAddSourceRecordId(builder, sourceRecordId)

def SemanticProvenanceDataAddArtifactSha256(builder, artifactSha256):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(artifactSha256), 0)

def AddArtifactSha256(builder, artifactSha256):
    SemanticProvenanceDataAddArtifactSha256(builder, artifactSha256)

def SemanticProvenanceDataAddDerivation(builder, derivation):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(derivation), 0)

def AddDerivation(builder, derivation):
    SemanticProvenanceDataAddDerivation(builder, derivation)

def SemanticProvenanceDataAddAuthoredOverrideId(builder, authoredOverrideId):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(authoredOverrideId), 0)

def AddAuthoredOverrideId(builder, authoredOverrideId):
    SemanticProvenanceDataAddAuthoredOverrideId(builder, authoredOverrideId)

def SemanticProvenanceDataEnd(builder):
    return builder.EndObject()

def End(builder):
    return SemanticProvenanceDataEnd(builder)


class SemanticProvenanceDataT(object):

    # SemanticProvenanceDataT
    def __init__(
        self,
        kind = None,
        sourceId = None,
        sourceRecordId = None,
        artifactSha256 = None,
        derivation = None,
        authoredOverrideId = None,
    ):
        self.kind = kind  # type: Optional[str]
        self.sourceId = sourceId  # type: Optional[str]
        self.sourceRecordId = sourceRecordId  # type: Optional[str]
        self.artifactSha256 = artifactSha256  # type: Optional[str]
        self.derivation = derivation  # type: Optional[str]
        self.authoredOverrideId = authoredOverrideId  # type: Optional[str]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        semanticProvenanceData = SemanticProvenanceData()
        semanticProvenanceData.Init(buf, pos)
        return cls.InitFromObj(semanticProvenanceData)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, semanticProvenanceData):
        x = SemanticProvenanceDataT()
        x._UnPack(semanticProvenanceData)
        return x

    # SemanticProvenanceDataT
    def _UnPack(self, semanticProvenanceData):
        if semanticProvenanceData is None:
            return
        self.kind = semanticProvenanceData.Kind()
        self.sourceId = semanticProvenanceData.SourceId()
        self.sourceRecordId = semanticProvenanceData.SourceRecordId()
        self.artifactSha256 = semanticProvenanceData.ArtifactSha256()
        self.derivation = semanticProvenanceData.Derivation()
        self.authoredOverrideId = semanticProvenanceData.AuthoredOverrideId()

    # SemanticProvenanceDataT
    def Pack(self, builder):
        if self.kind is not None:
            kind = builder.CreateString(self.kind)
        if self.sourceId is not None:
            sourceId = builder.CreateString(self.sourceId)
        if self.sourceRecordId is not None:
            sourceRecordId = builder.CreateString(self.sourceRecordId)
        if self.artifactSha256 is not None:
            artifactSha256 = builder.CreateString(self.artifactSha256)
        if self.derivation is not None:
            derivation = builder.CreateString(self.derivation)
        if self.authoredOverrideId is not None:
            authoredOverrideId = builder.CreateString(self.authoredOverrideId)
        SemanticProvenanceDataStart(builder)
        if self.kind is not None:
            SemanticProvenanceDataAddKind(builder, kind)
        if self.sourceId is not None:
            SemanticProvenanceDataAddSourceId(builder, sourceId)
        if self.sourceRecordId is not None:
            SemanticProvenanceDataAddSourceRecordId(builder, sourceRecordId)
        if self.artifactSha256 is not None:
            SemanticProvenanceDataAddArtifactSha256(builder, artifactSha256)
        if self.derivation is not None:
            SemanticProvenanceDataAddDerivation(builder, derivation)
        if self.authoredOverrideId is not None:
            SemanticProvenanceDataAddAuthoredOverrideId(builder, authoredOverrideId)
        semanticProvenanceData = SemanticProvenanceDataEnd(builder)
        return semanticProvenanceData
