# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Content

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SimplifiedMapGeometryData(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SimplifiedMapGeometryData()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSimplifiedMapGeometryData(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def SimplifiedMapGeometryDataBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x43\x42\x52\x47", size_prefixed=size_prefixed)

    # SimplifiedMapGeometryData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SimplifiedMapGeometryData
    def EdgeId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SimplifiedMapGeometryData
    def Lod(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # SimplifiedMapGeometryData
    def Points(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 24
            from Cannonball.Content.SimplifiedMapPoint import SimplifiedMapPoint
            obj = SimplifiedMapPoint()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SimplifiedMapGeometryData
    def PointsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SimplifiedMapGeometryData
    def PointsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # SimplifiedMapGeometryData
    def ContentHash(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def SimplifiedMapGeometryDataStart(builder):
    builder.StartObject(4)

def Start(builder):
    SimplifiedMapGeometryDataStart(builder)

def SimplifiedMapGeometryDataAddEdgeId(builder, edgeId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(edgeId), 0)

def AddEdgeId(builder, edgeId):
    SimplifiedMapGeometryDataAddEdgeId(builder, edgeId)

def SimplifiedMapGeometryDataAddLod(builder, lod):
    builder.PrependUint32Slot(1, lod, 0)

def AddLod(builder, lod):
    SimplifiedMapGeometryDataAddLod(builder, lod)

def SimplifiedMapGeometryDataAddPoints(builder, points):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(points), 0)

def AddPoints(builder, points):
    SimplifiedMapGeometryDataAddPoints(builder, points)

def SimplifiedMapGeometryDataStartPointsVector(builder, numElems):
    return builder.StartVector(24, numElems, 8)

def StartPointsVector(builder, numElems):
    return SimplifiedMapGeometryDataStartPointsVector(builder, numElems)

def SimplifiedMapGeometryDataAddContentHash(builder, contentHash):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(contentHash), 0)

def AddContentHash(builder, contentHash):
    SimplifiedMapGeometryDataAddContentHash(builder, contentHash)

def SimplifiedMapGeometryDataEnd(builder):
    return builder.EndObject()

def End(builder):
    return SimplifiedMapGeometryDataEnd(builder)

import Cannonball.Content.SimplifiedMapPoint
try:
    from typing import List
except:
    pass

class SimplifiedMapGeometryDataT(object):

    # SimplifiedMapGeometryDataT
    def __init__(
        self,
        edgeId = None,
        lod = 0,
        points = None,
        contentHash = None,
    ):
        self.edgeId = edgeId  # type: Optional[str]
        self.lod = lod  # type: int
        self.points = points  # type: Optional[List[Cannonball.Content.SimplifiedMapPoint.SimplifiedMapPointT]]
        self.contentHash = contentHash  # type: Optional[str]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        simplifiedMapGeometryData = SimplifiedMapGeometryData()
        simplifiedMapGeometryData.Init(buf, pos)
        return cls.InitFromObj(simplifiedMapGeometryData)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, simplifiedMapGeometryData):
        x = SimplifiedMapGeometryDataT()
        x._UnPack(simplifiedMapGeometryData)
        return x

    # SimplifiedMapGeometryDataT
    def _UnPack(self, simplifiedMapGeometryData):
        if simplifiedMapGeometryData is None:
            return
        self.edgeId = simplifiedMapGeometryData.EdgeId()
        self.lod = simplifiedMapGeometryData.Lod()
        if not simplifiedMapGeometryData.PointsIsNone():
            self.points = []
            for i in range(simplifiedMapGeometryData.PointsLength()):
                if simplifiedMapGeometryData.Points(i) is None:
                    self.points.append(None)
                else:
                    simplifiedMapPoint_ = Cannonball.Content.SimplifiedMapPoint.SimplifiedMapPointT.InitFromObj(simplifiedMapGeometryData.Points(i))
                    self.points.append(simplifiedMapPoint_)
        self.contentHash = simplifiedMapGeometryData.ContentHash()

    # SimplifiedMapGeometryDataT
    def Pack(self, builder):
        if self.edgeId is not None:
            edgeId = builder.CreateString(self.edgeId)
        if self.points is not None:
            SimplifiedMapGeometryDataStartPointsVector(builder, len(self.points))
            for i in reversed(range(len(self.points))):
                self.points[i].Pack(builder)
            points = builder.EndVector()
        if self.contentHash is not None:
            contentHash = builder.CreateString(self.contentHash)
        SimplifiedMapGeometryDataStart(builder)
        if self.edgeId is not None:
            SimplifiedMapGeometryDataAddEdgeId(builder, edgeId)
        SimplifiedMapGeometryDataAddLod(builder, self.lod)
        if self.points is not None:
            SimplifiedMapGeometryDataAddPoints(builder, points)
        if self.contentHash is not None:
            SimplifiedMapGeometryDataAddContentHash(builder, contentHash)
        simplifiedMapGeometryData = SimplifiedMapGeometryDataEnd(builder)
        return simplifiedMapGeometryData
