# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Content

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SimplifiedMapPoint(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 24

    # SimplifiedMapPoint
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SimplifiedMapPoint
    def XMeters(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # SimplifiedMapPoint
    def YMeters(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))
    # SimplifiedMapPoint
    def EdgeDistanceMeters(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(16))

def CreateSimplifiedMapPoint(builder, xMeters, yMeters, edgeDistanceMeters):
    builder.Prep(8, 24)
    builder.PrependFloat64(edgeDistanceMeters)
    builder.PrependFloat64(yMeters)
    builder.PrependFloat64(xMeters)
    return builder.Offset()


class SimplifiedMapPointT(object):

    # SimplifiedMapPointT
    def __init__(
        self,
        xMeters = 0.0,
        yMeters = 0.0,
        edgeDistanceMeters = 0.0,
    ):
        self.xMeters = xMeters  # type: float
        self.yMeters = yMeters  # type: float
        self.edgeDistanceMeters = edgeDistanceMeters  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        simplifiedMapPoint = SimplifiedMapPoint()
        simplifiedMapPoint.Init(buf, pos)
        return cls.InitFromObj(simplifiedMapPoint)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, simplifiedMapPoint):
        x = SimplifiedMapPointT()
        x._UnPack(simplifiedMapPoint)
        return x

    # SimplifiedMapPointT
    def _UnPack(self, simplifiedMapPoint):
        if simplifiedMapPoint is None:
            return
        self.xMeters = simplifiedMapPoint.XMeters()
        self.yMeters = simplifiedMapPoint.YMeters()
        self.edgeDistanceMeters = simplifiedMapPoint.EdgeDistanceMeters()

    # SimplifiedMapPointT
    def Pack(self, builder):
        return CreateSimplifiedMapPoint(builder, self.xMeters, self.yMeters, self.edgeDistanceMeters)
