# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Content

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SourceProvenanceData(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SourceProvenanceData()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSourceProvenanceData(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def SourceProvenanceDataBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x43\x42\x52\x47", size_prefixed=size_prefixed)

    # SourceProvenanceData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SourceProvenanceData
    def SourceId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SourceProvenanceData
    def Publisher(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SourceProvenanceData
    def SourceUrl(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SourceProvenanceData
    def ArtifactSha256(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SourceProvenanceData
    def AcquisitionLockSha256(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def SourceProvenanceDataStart(builder):
    builder.StartObject(5)

def Start(builder):
    SourceProvenanceDataStart(builder)

def SourceProvenanceDataAddSourceId(builder, sourceId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(sourceId), 0)

def AddSourceId(builder, sourceId):
    SourceProvenanceDataAddSourceId(builder, sourceId)

def SourceProvenanceDataAddPublisher(builder, publisher):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(publisher), 0)

def AddPublisher(builder, publisher):
    SourceProvenanceDataAddPublisher(builder, publisher)

def SourceProvenanceDataAddSourceUrl(builder, sourceUrl):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(sourceUrl), 0)

def AddSourceUrl(builder, sourceUrl):
    SourceProvenanceDataAddSourceUrl(builder, sourceUrl)

def SourceProvenanceDataAddArtifactSha256(builder, artifactSha256):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(artifactSha256), 0)

def AddArtifactSha256(builder, artifactSha256):
    SourceProvenanceDataAddArtifactSha256(builder, artifactSha256)

def SourceProvenanceDataAddAcquisitionLockSha256(builder, acquisitionLockSha256):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(acquisitionLockSha256), 0)

def AddAcquisitionLockSha256(builder, acquisitionLockSha256):
    SourceProvenanceDataAddAcquisitionLockSha256(builder, acquisitionLockSha256)

def SourceProvenanceDataEnd(builder):
    return builder.EndObject()

def End(builder):
    return SourceProvenanceDataEnd(builder)


class SourceProvenanceDataT(object):

    # SourceProvenanceDataT
    def __init__(
        self,
        sourceId = None,
        publisher = None,
        sourceUrl = None,
        artifactSha256 = None,
        acquisitionLockSha256 = None,
    ):
        self.sourceId = sourceId  # type: Optional[str]
        self.publisher = publisher  # type: Optional[str]
        self.sourceUrl = sourceUrl  # type: Optional[str]
        self.artifactSha256 = artifactSha256  # type: Optional[str]
        self.acquisitionLockSha256 = acquisitionLockSha256  # type: Optional[str]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        sourceProvenanceData = SourceProvenanceData()
        sourceProvenanceData.Init(buf, pos)
        return cls.InitFromObj(sourceProvenanceData)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, sourceProvenanceData):
        x = SourceProvenanceDataT()
        x._UnPack(sourceProvenanceData)
        return x

    # SourceProvenanceDataT
    def _UnPack(self, sourceProvenanceData):
        if sourceProvenanceData is None:
            return
        self.sourceId = sourceProvenanceData.SourceId()
        self.publisher = sourceProvenanceData.Publisher()
        self.sourceUrl = sourceProvenanceData.SourceUrl()
        self.artifactSha256 = sourceProvenanceData.ArtifactSha256()
        self.acquisitionLockSha256 = sourceProvenanceData.AcquisitionLockSha256()

    # SourceProvenanceDataT
    def Pack(self, builder):
        if self.sourceId is not None:
            sourceId = builder.CreateString(self.sourceId)
        if self.publisher is not None:
            publisher = builder.CreateString(self.publisher)
        if self.sourceUrl is not None:
            sourceUrl = builder.CreateString(self.sourceUrl)
        if self.artifactSha256 is not None:
            artifactSha256 = builder.CreateString(self.artifactSha256)
        if self.acquisitionLockSha256 is not None:
            acquisitionLockSha256 = builder.CreateString(self.acquisitionLockSha256)
        SourceProvenanceDataStart(builder)
        if self.sourceId is not None:
            SourceProvenanceDataAddSourceId(builder, sourceId)
        if self.publisher is not None:
            SourceProvenanceDataAddPublisher(builder, publisher)
        if self.sourceUrl is not None:
            SourceProvenanceDataAddSourceUrl(builder, sourceUrl)
        if self.artifactSha256 is not None:
            SourceProvenanceDataAddArtifactSha256(builder, artifactSha256)
        if self.acquisitionLockSha256 is not None:
            SourceProvenanceDataAddAcquisitionLockSha256(builder, acquisitionLockSha256)
        sourceProvenanceData = SourceProvenanceDataEnd(builder)
        return sourceProvenanceData
