# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Content

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SourceCoordinate(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 24

    # SourceCoordinate
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SourceCoordinate
    def Longitude(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # SourceCoordinate
    def Latitude(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))
    # SourceCoordinate
    def ElevationMeters(self): return self._tab.Get(flatbuffers.number_types.Float64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(16))

def CreateSourceCoordinate(builder, longitude, latitude, elevationMeters):
    builder.Prep(8, 24)
    builder.PrependFloat64(elevationMeters)
    builder.PrependFloat64(latitude)
    builder.PrependFloat64(longitude)
    return builder.Offset()


class SourceCoordinateT(object):

    # SourceCoordinateT
    def __init__(
        self,
        longitude = 0.0,
        latitude = 0.0,
        elevationMeters = 0.0,
    ):
        self.longitude = longitude  # type: float
        self.latitude = latitude  # type: float
        self.elevationMeters = elevationMeters  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        sourceCoordinate = SourceCoordinate()
        sourceCoordinate.Init(buf, pos)
        return cls.InitFromObj(sourceCoordinate)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, sourceCoordinate):
        x = SourceCoordinateT()
        x._UnPack(sourceCoordinate)
        return x

    # SourceCoordinateT
    def _UnPack(self, sourceCoordinate):
        if sourceCoordinate is None:
            return
        self.longitude = sourceCoordinate.Longitude()
        self.latitude = sourceCoordinate.Latitude()
        self.elevationMeters = sourceCoordinate.ElevationMeters()

    # SourceCoordinateT
    def Pack(self, builder):
        return CreateSourceCoordinate(builder, self.longitude, self.latitude, self.elevationMeters)
