# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Content

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SpatialReferenceData(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SpatialReferenceData()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSpatialReferenceData(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def SpatialReferenceDataBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x43\x42\x52\x47", size_prefixed=size_prefixed)

    # SpatialReferenceData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SpatialReferenceData
    def RouteCrs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SpatialReferenceData
    def ElevationCrs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SpatialReferenceData
    def HorizontalDatum(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SpatialReferenceData
    def VerticalDatum(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SpatialReferenceData
    def ElevationUnits(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SpatialReferenceData
    def ElevationProductId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SpatialReferenceData
    def ElevationProductTitle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SpatialReferenceData
    def ElevationProductResolution(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SpatialReferenceData
    def ElevationArtifactSha256(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def SpatialReferenceDataStart(builder):
    builder.StartObject(9)

def Start(builder):
    SpatialReferenceDataStart(builder)

def SpatialReferenceDataAddRouteCrs(builder, routeCrs):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(routeCrs), 0)

def AddRouteCrs(builder, routeCrs):
    SpatialReferenceDataAddRouteCrs(builder, routeCrs)

def SpatialReferenceDataAddElevationCrs(builder, elevationCrs):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(elevationCrs), 0)

def AddElevationCrs(builder, elevationCrs):
    SpatialReferenceDataAddElevationCrs(builder, elevationCrs)

def SpatialReferenceDataAddHorizontalDatum(builder, horizontalDatum):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(horizontalDatum), 0)

def AddHorizontalDatum(builder, horizontalDatum):
    SpatialReferenceDataAddHorizontalDatum(builder, horizontalDatum)

def SpatialReferenceDataAddVerticalDatum(builder, verticalDatum):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(verticalDatum), 0)

def AddVerticalDatum(builder, verticalDatum):
    SpatialReferenceDataAddVerticalDatum(builder, verticalDatum)

def SpatialReferenceDataAddElevationUnits(builder, elevationUnits):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(elevationUnits), 0)

def AddElevationUnits(builder, elevationUnits):
    SpatialReferenceDataAddElevationUnits(builder, elevationUnits)

def SpatialReferenceDataAddElevationProductId(builder, elevationProductId):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(elevationProductId), 0)

def AddElevationProductId(builder, elevationProductId):
    SpatialReferenceDataAddElevationProductId(builder, elevationProductId)

def SpatialReferenceDataAddElevationProductTitle(builder, elevationProductTitle):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(elevationProductTitle), 0)

def AddElevationProductTitle(builder, elevationProductTitle):
    SpatialReferenceDataAddElevationProductTitle(builder, elevationProductTitle)

def SpatialReferenceDataAddElevationProductResolution(builder, elevationProductResolution):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(elevationProductResolution), 0)

def AddElevationProductResolution(builder, elevationProductResolution):
    SpatialReferenceDataAddElevationProductResolution(builder, elevationProductResolution)

def SpatialReferenceDataAddElevationArtifactSha256(builder, elevationArtifactSha256):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(elevationArtifactSha256), 0)

def AddElevationArtifactSha256(builder, elevationArtifactSha256):
    SpatialReferenceDataAddElevationArtifactSha256(builder, elevationArtifactSha256)

def SpatialReferenceDataEnd(builder):
    return builder.EndObject()

def End(builder):
    return SpatialReferenceDataEnd(builder)


class SpatialReferenceDataT(object):

    # SpatialReferenceDataT
    def __init__(
        self,
        routeCrs = None,
        elevationCrs = None,
        horizontalDatum = None,
        verticalDatum = None,
        elevationUnits = None,
        elevationProductId = None,
        elevationProductTitle = None,
        elevationProductResolution = None,
        elevationArtifactSha256 = None,
    ):
        self.routeCrs = routeCrs  # type: Optional[str]
        self.elevationCrs = elevationCrs  # type: Optional[str]
        self.horizontalDatum = horizontalDatum  # type: Optional[str]
        self.verticalDatum = verticalDatum  # type: Optional[str]
        self.elevationUnits = elevationUnits  # type: Optional[str]
        self.elevationProductId = elevationProductId  # type: Optional[str]
        self.elevationProductTitle = elevationProductTitle  # type: Optional[str]
        self.elevationProductResolution = elevationProductResolution  # type: Optional[str]
        self.elevationArtifactSha256 = elevationArtifactSha256  # type: Optional[str]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        spatialReferenceData = SpatialReferenceData()
        spatialReferenceData.Init(buf, pos)
        return cls.InitFromObj(spatialReferenceData)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, spatialReferenceData):
        x = SpatialReferenceDataT()
        x._UnPack(spatialReferenceData)
        return x

    # SpatialReferenceDataT
    def _UnPack(self, spatialReferenceData):
        if spatialReferenceData is None:
            return
        self.routeCrs = spatialReferenceData.RouteCrs()
        self.elevationCrs = spatialReferenceData.ElevationCrs()
        self.horizontalDatum = spatialReferenceData.HorizontalDatum()
        self.verticalDatum = spatialReferenceData.VerticalDatum()
        self.elevationUnits = spatialReferenceData.ElevationUnits()
        self.elevationProductId = spatialReferenceData.ElevationProductId()
        self.elevationProductTitle = spatialReferenceData.ElevationProductTitle()
        self.elevationProductResolution = spatialReferenceData.ElevationProductResolution()
        self.elevationArtifactSha256 = spatialReferenceData.ElevationArtifactSha256()

    # SpatialReferenceDataT
    def Pack(self, builder):
        if self.routeCrs is not None:
            routeCrs = builder.CreateString(self.routeCrs)
        if self.elevationCrs is not None:
            elevationCrs = builder.CreateString(self.elevationCrs)
        if self.horizontalDatum is not None:
            horizontalDatum = builder.CreateString(self.horizontalDatum)
        if self.verticalDatum is not None:
            verticalDatum = builder.CreateString(self.verticalDatum)
        if self.elevationUnits is not None:
            elevationUnits = builder.CreateString(self.elevationUnits)
        if self.elevationProductId is not None:
            elevationProductId = builder.CreateString(self.elevationProductId)
        if self.elevationProductTitle is not None:
            elevationProductTitle = builder.CreateString(self.elevationProductTitle)
        if self.elevationProductResolution is not None:
            elevationProductResolution = builder.CreateString(self.elevationProductResolution)
        if self.elevationArtifactSha256 is not None:
            elevationArtifactSha256 = builder.CreateString(self.elevationArtifactSha256)
        SpatialReferenceDataStart(builder)
        if self.routeCrs is not None:
            SpatialReferenceDataAddRouteCrs(builder, routeCrs)
        if self.elevationCrs is not None:
            SpatialReferenceDataAddElevationCrs(builder, elevationCrs)
        if self.horizontalDatum is not None:
            SpatialReferenceDataAddHorizontalDatum(builder, horizontalDatum)
        if self.verticalDatum is not None:
            SpatialReferenceDataAddVerticalDatum(builder, verticalDatum)
        if self.elevationUnits is not None:
            SpatialReferenceDataAddElevationUnits(builder, elevationUnits)
        if self.elevationProductId is not None:
            SpatialReferenceDataAddElevationProductId(builder, elevationProductId)
        if self.elevationProductTitle is not None:
            SpatialReferenceDataAddElevationProductTitle(builder, elevationProductTitle)
        if self.elevationProductResolution is not None:
            SpatialReferenceDataAddElevationProductResolution(builder, elevationProductResolution)
        if self.elevationArtifactSha256 is not None:
            SpatialReferenceDataAddElevationArtifactSha256(builder, elevationArtifactSha256)
        spatialReferenceData = SpatialReferenceDataEnd(builder)
        return spatialReferenceData
